/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.AudiofilesApi

class AudiofilesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AudiofilesApi
        //val apiInstance = AudiofilesApi()

        // to test audiofilesGetTuneFromAbsolutePathAudiofilesPath
        should("test audiofilesGetTuneFromAbsolutePathAudiofilesPath") {
            // uncomment below to test audiofilesGetTuneFromAbsolutePathAudiofilesPath
            //val path : kotlin.String = path_example // kotlin.String | path to search the tune
            //apiInstance.audiofilesGetTuneFromAbsolutePathAudiofilesPath(path)
        }

        // to test audiofilesRelocateAudioFilesAudiofilesRelocateAll
        should("test audiofilesRelocateAudioFilesAudiofilesRelocateAll") {
            // uncomment below to test audiofilesRelocateAudioFilesAudiofilesRelocateAll
            //val oldPath : kotlin.String = oldPath_example // kotlin.String | old path
            //val newPath : kotlin.String = newPath_example // kotlin.String | new path 
            //apiInstance.audiofilesRelocateAudioFilesAudiofilesRelocateAll(oldPath, newPath)
        }

        // to test audiofilesUpdateAudioFilePathAudiofilesPath
        should("test audiofilesUpdateAudioFilePathAudiofilesPath") {
            // uncomment below to test audiofilesUpdateAudioFilePathAudiofilesPath
            //val tuneId : kotlin.String = tuneId_example // kotlin.String | tune id
            //val audiofileId : kotlin.String = audiofileId_example // kotlin.String | audioFile Id
            //val newPath : kotlin.String = newPath_example // kotlin.String | path to search the tune
            //apiInstance.audiofilesUpdateAudioFilePathAudiofilesPath(tuneId, audiofileId, newPath)
        }

    }
}
