/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.BackendApi

class BackendApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BackendApi
        //val apiInstance = BackendApi()

        // to test backendGetServerIPAddressBackendServerIpAddress
        should("test backendGetServerIPAddressBackendServerIpAddress") {
            // uncomment below to test backendGetServerIPAddressBackendServerIpAddress
            //apiInstance.backendGetServerIPAddressBackendServerIpAddress()
        }

        // to test backendListAllTasksBackendBackgroundTasks
        should("test backendListAllTasksBackendBackgroundTasks") {
            // uncomment below to test backendListAllTasksBackendBackgroundTasks
            //apiInstance.backendListAllTasksBackendBackgroundTasks()
        }

        // to test backendOpenTerminalAndTailLogsBackendOpenTerminalAndTailLogs
        should("test backendOpenTerminalAndTailLogsBackendOpenTerminalAndTailLogs") {
            // uncomment below to test backendOpenTerminalAndTailLogsBackendOpenTerminalAndTailLogs
            //apiInstance.backendOpenTerminalAndTailLogsBackendOpenTerminalAndTailLogs()
        }

        // to test backendPauseTaskBackendBackgroundTasksTaskIdPause
        should("test backendPauseTaskBackendBackgroundTasksTaskIdPause") {
            // uncomment below to test backendPauseTaskBackendBackgroundTasksTaskIdPause
            //val taskId : kotlin.String = taskId_example // kotlin.String | 
            //apiInstance.backendPauseTaskBackendBackgroundTasksTaskIdPause(taskId)
        }

        // to test backendPingBackendPing
        should("test backendPingBackendPing") {
            // uncomment below to test backendPingBackendPing
            //apiInstance.backendPingBackendPing()
        }

        // to test backendResumeTaskBackendBackgroundTasksTaskIdResume
        should("test backendResumeTaskBackendBackgroundTasksTaskIdResume") {
            // uncomment below to test backendResumeTaskBackendBackgroundTasksTaskIdResume
            //val taskId : kotlin.String = taskId_example // kotlin.String | 
            //apiInstance.backendResumeTaskBackendBackgroundTasksTaskIdResume(taskId)
        }

        // to test backendShutDownBackendShutdown
        should("test backendShutDownBackendShutdown") {
            // uncomment below to test backendShutDownBackendShutdown
            //apiInstance.backendShutDownBackendShutdown()
        }

        // to test backendStopTaskBackendBackgroundTasksTaskIdStop
        should("test backendStopTaskBackendBackgroundTasksTaskIdStop") {
            // uncomment below to test backendStopTaskBackendBackgroundTasksTaskIdStop
            //val taskId : kotlin.String = taskId_example // kotlin.String | 
            //apiInstance.backendStopTaskBackendBackgroundTasksTaskIdStop(taskId)
        }

        // to test backendTestBackendTest
        should("test backendTestBackendTest") {
            // uncomment below to test backendTestBackendTest
            //apiInstance.backendTestBackendTest()
        }

    }
}
