/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.CrateTypesApi
import io.crates.api.models.CrateTypePresentationBean

class CrateTypesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CrateTypesApi
        //val apiInstance = CrateTypesApi()

        // to test crateTypesGetAllCrateTypes
        should("test crateTypesGetAllCrateTypes") {
            // uncomment below to test crateTypesGetAllCrateTypes
            //val result : kotlin.collections.List<CrateTypePresentationBean> = apiInstance.crateTypesGetAllCrateTypes()
            //result shouldBe ("TODO")
        }

        // to test crateTypesGetAllTypesCrateTypesFrontEndRenderTypes
        should("test crateTypesGetAllTypesCrateTypesFrontEndRenderTypes") {
            // uncomment below to test crateTypesGetAllTypesCrateTypesFrontEndRenderTypes
            //val result : kotlin.collections.List<CrateTypePresentationBean> = apiInstance.crateTypesGetAllTypesCrateTypesFrontEndRenderTypes()
            //result shouldBe ("TODO")
        }

    }
}
