/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.ExternalDevicesApi
import io.crates.api.models.USBExternalStorageDevicePresentationBean

class ExternalDevicesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExternalDevicesApi
        //val apiInstance = ExternalDevicesApi()

        // to test externalDevicesGetAllExternalDevicesExternalDevices
        should("test externalDevicesGetAllExternalDevicesExternalDevices") {
            // uncomment below to test externalDevicesGetAllExternalDevicesExternalDevices
            //val result : kotlin.collections.List<USBExternalStorageDevicePresentationBean> = apiInstance.externalDevicesGetAllExternalDevicesExternalDevices()
            //result shouldBe ("TODO")
        }

        // to test externalDevicesImportTunesFromExternalDeviceExternalDevicesImport
        should("test externalDevicesImportTunesFromExternalDeviceExternalDevicesImport") {
            // uncomment below to test externalDevicesImportTunesFromExternalDeviceExternalDevicesImport
            //val name : kotlin.String = name_example // kotlin.String | the deviceName
            //val path : kotlin.String = path_example // kotlin.String | the device root path
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //apiInstance.externalDevicesImportTunesFromExternalDeviceExternalDevicesImport(name, path, clientID, callbacks)
        }

        // to test externalDevicesTestExternalDevicesTest
        should("test externalDevicesTestExternalDevicesTest") {
            // uncomment below to test externalDevicesTestExternalDevicesTest
            //apiInstance.externalDevicesTestExternalDevicesTest()
        }

    }
}
