/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.GeniusApi

class GeniusApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GeniusApi
        //val apiInstance = GeniusApi()

        // to test geniusSearchLyricsGeniusSearchTuneID
        should("test geniusSearchLyricsGeniusSearchTuneID") {
            // uncomment below to test geniusSearchLyricsGeniusSearchTuneID
            //val tuneID : kotlin.String = tuneID_example // kotlin.String | the code
            //apiInstance.geniusSearchLyricsGeniusSearchTuneID(tuneID)
        }

        // to test geniusVerifyGeniusVerification
        should("test geniusVerifyGeniusVerification") {
            // uncomment below to test geniusVerifyGeniusVerification
            //val code : kotlin.String = code_example // kotlin.String | the code
            //apiInstance.geniusVerifyGeniusVerification(code)
        }

    }
}
