/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.ItunesApi

class ItunesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ItunesApi
        //val apiInstance = ItunesApi()

        // to test itunesExportToItunesItunesExport
        should("test itunesExportToItunesItunesExport") {
            // uncomment below to test itunesExportToItunesItunesExport
            //val path : kotlin.String = path_example // kotlin.String | the absolute path to store the file
            //apiInstance.itunesExportToItunesItunesExport(path)
        }

        // to test itunesGetTestItunesTest
        should("test itunesGetTestItunesTest") {
            // uncomment below to test itunesGetTestItunesTest
            //apiInstance.itunesGetTestItunesTest()
        }

        // to test itunesImportFromItunesItunesImport
        should("test itunesImportFromItunesItunesImport") {
            // uncomment below to test itunesImportFromItunesItunesImport
            //val file : kotlin.String = file_example // kotlin.String | the absolute path of the itunes xml file
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val allow : kotlin.String = allow_example // kotlin.String | set true if you want the override crates datecreated with itunes date added one
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //apiInstance.itunesImportFromItunesItunesImport(file, clientID, allow, callbacks)
        }

        // to test itunesImportItunesCompatibleXMLItunesImportItunesCompatibleXml
        should("test itunesImportItunesCompatibleXMLItunesImportItunesCompatibleXml") {
            // uncomment below to test itunesImportItunesCompatibleXMLItunesImportItunesCompatibleXml
            //val path : kotlin.String = path_example // kotlin.String | the absolute path of the itunes compatible xml file
            //val crateId : kotlin.String = crateId_example // kotlin.String | The crate under which to import the collection described in the xml 
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //apiInstance.itunesImportItunesCompatibleXMLItunesImportItunesCompatibleXml(path, crateId, clientID, callbacks)
        }

    }
}
