/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.LogsApi
import io.crates.api.models.EventLogPresentationBean

class LogsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LogsApi
        //val apiInstance = LogsApi()

        // to test logsDeleteByIdLogsId
        should("test logsDeleteByIdLogsId") {
            // uncomment below to test logsDeleteByIdLogsId
            //val id : kotlin.String = id_example // kotlin.String | The id of the log to delete
            //apiInstance.logsDeleteByIdLogsId(id)
        }

        // to test logsGetAllLogsLogs
        should("test logsGetAllLogsLogs") {
            // uncomment below to test logsGetAllLogsLogs
            //val result : kotlin.collections.List<EventLogPresentationBean> = apiInstance.logsGetAllLogsLogs()
            //result shouldBe ("TODO")
        }

        // to test logsGetLogByIDLogsId
        should("test logsGetLogByIDLogsId") {
            // uncomment below to test logsGetLogByIDLogsId
            //val id : kotlin.String = id_example // kotlin.String | The id of the log
            //val result : EventLogPresentationBean = apiInstance.logsGetLogByIDLogsId(id)
            //result shouldBe ("TODO")
        }

        // to test logsGetLogLevelLogsLevel
        should("test logsGetLogLevelLogsLevel") {
            // uncomment below to test logsGetLogLevelLogsLevel
            //val loggerName : kotlin.String = loggerName_example // kotlin.String | The name of the logger
            //apiInstance.logsGetLogLevelLogsLevel(loggerName)
        }

        // to test logsGetLogsByActionTypeIDLogsActionTypesEventTypeId
        should("test logsGetLogsByActionTypeIDLogsActionTypesEventTypeId") {
            // uncomment below to test logsGetLogsByActionTypeIDLogsActionTypesEventTypeId
            //val eventTypeId : kotlin.String = eventTypeId_example // kotlin.String | The id of the action type to get its logs
            //val result : kotlin.collections.List<EventLogPresentationBean> = apiInstance.logsGetLogsByActionTypeIDLogsActionTypesEventTypeId(eventTypeId)
            //result shouldBe ("TODO")
        }

        // to test logsSetLogLevelLogsSetLevel
        should("test logsSetLogLevelLogsSetLevel") {
            // uncomment below to test logsSetLogLevelLogsSetLevel
            //val body : kotlin.String = body_example // kotlin.String | 
            //apiInstance.logsSetLogLevelLogsSetLevel(body)
        }

    }
}
