/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.NewsfeedApi

class NewsfeedApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NewsfeedApi
        //val apiInstance = NewsfeedApi()

        // to test newsfeedPopulateFromArtistNewsfeedPopulateArtist
        should("test newsfeedPopulateFromArtistNewsfeedPopulateArtist") {
            // uncomment below to test newsfeedPopulateFromArtistNewsfeedPopulateArtist
            //val `value` : kotlin.String = `value`_example // kotlin.String | the artist name
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //apiInstance.newsfeedPopulateFromArtistNewsfeedPopulateArtist(`value`, clientID, callbacks)
        }

        // to test newsfeedPopulateFromDateNewsfeedPopulate
        should("test newsfeedPopulateFromDateNewsfeedPopulate") {
            // uncomment below to test newsfeedPopulateFromDateNewsfeedPopulate
            //val datefrom : kotlin.String = datefrom_example // kotlin.String | the dateFrom which to get the user interests to populate newsfeed
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //apiInstance.newsfeedPopulateFromDateNewsfeedPopulate(datefrom, clientID, callbacks)
        }

        // to test newsfeedPopulateFromLabelNewsfeedPopulateLabel
        should("test newsfeedPopulateFromLabelNewsfeedPopulateLabel") {
            // uncomment below to test newsfeedPopulateFromLabelNewsfeedPopulateLabel
            //val `value` : kotlin.String = `value`_example // kotlin.String | the label name
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //apiInstance.newsfeedPopulateFromLabelNewsfeedPopulateLabel(`value`, clientID, callbacks)
        }

    }
}
