/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.PlayerTargetApi
import io.crates.api.models.PlayerTargetDescription

class PlayerTargetApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerTargetApi
        //val apiInstance = PlayerTargetApi()

        // to test playerTargetAddTargetPlayerPlayerTarget
        should("test playerTargetAddTargetPlayerPlayerTarget") {
            // uncomment below to test playerTargetAddTargetPlayerPlayerTarget
            //val body : kotlin.String = body_example // kotlin.String | 
            //val result : kotlin.collections.List<PlayerTargetDescription> = apiInstance.playerTargetAddTargetPlayerPlayerTarget(body)
            //result shouldBe ("TODO")
        }

        // to test playerTargetGetAllTargetPlayersPlayerTarget
        should("test playerTargetGetAllTargetPlayersPlayerTarget") {
            // uncomment below to test playerTargetGetAllTargetPlayersPlayerTarget
            //val result : kotlin.collections.List<PlayerTargetDescription> = apiInstance.playerTargetGetAllTargetPlayersPlayerTarget()
            //result shouldBe ("TODO")
        }

        // to test playerTargetGetAllTypesPlayerTargetTypes
        should("test playerTargetGetAllTypesPlayerTargetTypes") {
            // uncomment below to test playerTargetGetAllTypesPlayerTargetTypes
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.playerTargetGetAllTypesPlayerTargetTypes()
            //result shouldBe ("TODO")
        }

        // to test playerTargetGetTargetPlayerPlayerTargetId
        should("test playerTargetGetTargetPlayerPlayerTargetId") {
            // uncomment below to test playerTargetGetTargetPlayerPlayerTargetId
            //val id : kotlin.String = id_example // kotlin.String | the id of the target player
            //val result : PlayerTargetDescription = apiInstance.playerTargetGetTargetPlayerPlayerTargetId(id)
            //result shouldBe ("TODO")
        }

        // to test playerTargetRemoveTargetPlayerPlayerTargetIdRemove
        should("test playerTargetRemoveTargetPlayerPlayerTargetIdRemove") {
            // uncomment below to test playerTargetRemoveTargetPlayerPlayerTargetIdRemove
            //val id : kotlin.String = id_example // kotlin.String | the id of the target player
            //val result : kotlin.collections.List<PlayerTargetDescription> = apiInstance.playerTargetRemoveTargetPlayerPlayerTargetIdRemove(id)
            //result shouldBe ("TODO")
        }

    }
}
