/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.PlayLocalApi
import io.crates.api.models.PlayQueuePreviousContext
import io.crates.api.models.PlayerStartedPresentationBean
import io.crates.api.models.PlayerTargetDescription

class PlayLocalApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayLocalApi
        //val apiInstance = PlayLocalApi()

        // to test playLocalGetAllServerEventsPlayLocalEvents
        should("test playLocalGetAllServerEventsPlayLocalEvents") {
            // uncomment below to test playLocalGetAllServerEventsPlayLocalEvents
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.playLocalGetAllServerEventsPlayLocalEvents()
            //result shouldBe ("TODO")
        }

        // to test playLocalGetAudioSourceTypesPlayLocalAudiosourceTypes
        should("test playLocalGetAudioSourceTypesPlayLocalAudiosourceTypes") {
            // uncomment below to test playLocalGetAudioSourceTypesPlayLocalAudiosourceTypes
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.playLocalGetAudioSourceTypesPlayLocalAudiosourceTypes()
            //result shouldBe ("TODO")
        }

        // to test playLocalGetNextTunePlayLocalPlayerQueueNext
        should("test playLocalGetNextTunePlayLocalPlayerQueueNext") {
            // uncomment below to test playLocalGetNextTunePlayLocalPlayerQueueNext
            //apiInstance.playLocalGetNextTunePlayLocalPlayerQueueNext()
        }

        // to test playLocalGetPlayQueueControlerStatusesPlayLocalPlayQueuePlayerStatus
        should("test playLocalGetPlayQueueControlerStatusesPlayLocalPlayQueuePlayerStatus") {
            // uncomment below to test playLocalGetPlayQueueControlerStatusesPlayLocalPlayQueuePlayerStatus
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.playLocalGetPlayQueueControlerStatusesPlayLocalPlayQueuePlayerStatus()
            //result shouldBe ("TODO")
        }

        // to test playLocalGetPlayQueueControllerRepeatPoliciesPlayLocalPlayQueuePoliciesRepeat
        should("test playLocalGetPlayQueueControllerRepeatPoliciesPlayLocalPlayQueuePoliciesRepeat") {
            // uncomment below to test playLocalGetPlayQueueControllerRepeatPoliciesPlayLocalPlayQueuePoliciesRepeat
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.playLocalGetPlayQueueControllerRepeatPoliciesPlayLocalPlayQueuePoliciesRepeat()
            //result shouldBe ("TODO")
        }

        // to test playLocalGetPlayQueueControllerShufflePoliciesPlayLocalPlayQueuePoliciesShuffle
        should("test playLocalGetPlayQueueControllerShufflePoliciesPlayLocalPlayQueuePoliciesShuffle") {
            // uncomment below to test playLocalGetPlayQueueControllerShufflePoliciesPlayLocalPlayQueuePoliciesShuffle
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.playLocalGetPlayQueueControllerShufflePoliciesPlayLocalPlayQueuePoliciesShuffle()
            //result shouldBe ("TODO")
        }

        // to test playLocalGetPlayerQueueInfoPlayLocalPlayerQueueInfo
        should("test playLocalGetPlayerQueueInfoPlayLocalPlayerQueueInfo") {
            // uncomment below to test playLocalGetPlayerQueueInfoPlayLocalPlayerQueueInfo
            //val result : PlayQueuePreviousContext = apiInstance.playLocalGetPlayerQueueInfoPlayLocalPlayerQueueInfo()
            //result shouldBe ("TODO")
        }

        // to test playLocalNextPlayLocalPlayQueueNext
        should("test playLocalNextPlayLocalPlayQueueNext") {
            // uncomment below to test playLocalNextPlayLocalPlayQueueNext
            //apiInstance.playLocalNextPlayLocalPlayQueueNext()
        }

        // to test playLocalPausePlayLocalPause
        should("test playLocalPausePlayLocalPause") {
            // uncomment below to test playLocalPausePlayLocalPause
            //apiInstance.playLocalPausePlayLocalPause()
        }

        // to test playLocalPausePlayQueuePlayLocalPlayQueuePause
        should("test playLocalPausePlayQueuePlayLocalPlayQueuePause") {
            // uncomment below to test playLocalPausePlayQueuePlayLocalPlayQueuePause
            //apiInstance.playLocalPausePlayQueuePlayLocalPlayQueuePause()
        }

        // to test playLocalPlayFromAudioSourcePlayLocalPlayQueueCratesCrateIdAudiosourceAudiosourceIdTypeType
        should("test playLocalPlayFromAudioSourcePlayLocalPlayQueueCratesCrateIdAudiosourceAudiosourceIdTypeType") {
            // uncomment below to test playLocalPlayFromAudioSourcePlayLocalPlayQueueCratesCrateIdAudiosourceAudiosourceIdTypeType
            //val crateId : kotlin.String = crateId_example // kotlin.String | the id of the active crate/playlist to notify the playqueue
            //val audiosourceId : kotlin.String = audiosourceId_example // kotlin.String | the id of the audiosource to play
            //val type : kotlin.String = type_example // kotlin.String | the type of the audiosource to play
            //val result : PlayerStartedPresentationBean = apiInstance.playLocalPlayFromAudioSourcePlayLocalPlayQueueCratesCrateIdAudiosourceAudiosourceIdTypeType(crateId, audiosourceId, type)
            //result shouldBe ("TODO")
        }

        // to test playLocalPlayPlayLocalPlayQueueCratesCrateIdTunesTuneId
        should("test playLocalPlayPlayLocalPlayQueueCratesCrateIdTunesTuneId") {
            // uncomment below to test playLocalPlayPlayLocalPlayQueueCratesCrateIdTunesTuneId
            //val crateId : kotlin.String = crateId_example // kotlin.String | the id of the active crate/playlist to notify the playqueue
            //val tuneId : kotlin.String = tuneId_example // kotlin.String | the id of the tune to play
            //val tuneOrderId : kotlin.String = tuneOrderId_example // kotlin.String | the ordering id of the tune to play
            //val result : PlayerStartedPresentationBean = apiInstance.playLocalPlayPlayLocalPlayQueueCratesCrateIdTunesTuneId(crateId, tuneId, tuneOrderId)
            //result shouldBe ("TODO")
        }

        // to test playLocalPlayPlayQueuePlayLocalPlayQueuePlay
        should("test playLocalPlayPlayQueuePlayLocalPlayQueuePlay") {
            // uncomment below to test playLocalPlayPlayQueuePlayLocalPlayQueuePlay
            //apiInstance.playLocalPlayPlayQueuePlayLocalPlayQueuePlay()
        }

        // to test playLocalPrevPlayLocalPlayQueuePrev
        should("test playLocalPrevPlayLocalPlayQueuePrev") {
            // uncomment below to test playLocalPrevPlayLocalPlayQueuePrev
            //apiInstance.playLocalPrevPlayLocalPlayQueuePrev()
        }

        // to test playLocalSeekPlayLocalSeekValue
        should("test playLocalSeekPlayLocalSeekValue") {
            // uncomment below to test playLocalSeekPlayLocalSeekValue
            //val `value` : kotlin.String = `value`_example // kotlin.String | the value (in milisescs) of the track to seek to
            //apiInstance.playLocalSeekPlayLocalSeekValue(`value`)
        }

        // to test playLocalSeekPlayQueuePlayLocalPlayerQueueSeekValue
        should("test playLocalSeekPlayQueuePlayLocalPlayerQueueSeekValue") {
            // uncomment below to test playLocalSeekPlayQueuePlayLocalPlayerQueueSeekValue
            //val `value` : kotlin.String = `value`_example // kotlin.String | the value (in milisescs) of the track to seek to
            //apiInstance.playLocalSeekPlayQueuePlayLocalPlayerQueueSeekValue(`value`)
        }

        // to test playLocalSetPlayQueueControllerRepeatPolicyPlayLocalPlayQueuePoliciesRepeatSet
        should("test playLocalSetPlayQueueControllerRepeatPolicyPlayLocalPlayQueuePoliciesRepeatSet") {
            // uncomment below to test playLocalSetPlayQueueControllerRepeatPolicyPlayLocalPlayQueuePoliciesRepeatSet
            //val `value` : kotlin.String = `value`_example // kotlin.String | the new repeat policy for the PlayQueueControler
            //val clientID : kotlin.String = clientID_example // kotlin.String | The id of the client who requested the invocation of this service
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : kotlin.String = apiInstance.playLocalSetPlayQueueControllerRepeatPolicyPlayLocalPlayQueuePoliciesRepeatSet(`value`, clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test playLocalSetPlayQueueControllerShufflePolicyPlayLocalPlayQueuePoliciesShuffleSet
        should("test playLocalSetPlayQueueControllerShufflePolicyPlayLocalPlayQueuePoliciesShuffleSet") {
            // uncomment below to test playLocalSetPlayQueueControllerShufflePolicyPlayLocalPlayQueuePoliciesShuffleSet
            //val `value` : kotlin.String = `value`_example // kotlin.String | the new shuffle policy for the PlayQueueController
            //val clientID : kotlin.String = clientID_example // kotlin.String | The id of the client who requested the invocation of this service
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : kotlin.String = apiInstance.playLocalSetPlayQueueControllerShufflePolicyPlayLocalPlayQueuePoliciesShuffleSet(`value`, clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test playLocalSetTargetPlayerPlayLocalTargetPlayerId
        should("test playLocalSetTargetPlayerPlayLocalTargetPlayerId") {
            // uncomment below to test playLocalSetTargetPlayerPlayLocalTargetPlayerId
            //val id : kotlin.String = id_example // kotlin.String | the id of the target player
            //val playedAt : kotlin.String = playedAt_example // kotlin.String | the position for the target player to start playing
            //val result : PlayerTargetDescription = apiInstance.playLocalSetTargetPlayerPlayLocalTargetPlayerId(id, playedAt)
            //result shouldBe ("TODO")
        }

        // to test playLocalSetVolumePlayLocalVolumeValue
        should("test playLocalSetVolumePlayLocalVolumeValue") {
            // uncomment below to test playLocalSetVolumePlayLocalVolumeValue
            //val `value` : kotlin.String = `value`_example // kotlin.String | the volume of the player
            //val clientID : kotlin.String = clientID_example // kotlin.String | The id of the client who requested the invocation of this service
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //apiInstance.playLocalSetVolumePlayLocalVolumeValue(`value`, clientID, callbacks)
        }

        // to test playLocalStopPlayLocalStop
        should("test playLocalStopPlayLocalStop") {
            // uncomment below to test playLocalStopPlayLocalStop
            //apiInstance.playLocalStopPlayLocalStop()
        }

        // to test playLocalStreamAudioPlayLocalStreamId
        should("test playLocalStreamAudioPlayLocalStreamId") {
            // uncomment below to test playLocalStreamAudioPlayLocalStreamId
            //val range : kotlin.String = range_example // kotlin.String | header param indicating the range to play
            //val id : kotlin.String = id_example // kotlin.String | the id of the tune to stream over the network
            //apiInstance.playLocalStreamAudioPlayLocalStreamId(range, id)
        }

        // to test playLocalTuneEndedPlayLocalExternalTuneEnded
        should("test playLocalTuneEndedPlayLocalExternalTuneEnded") {
            // uncomment below to test playLocalTuneEndedPlayLocalExternalTuneEnded
            //apiInstance.playLocalTuneEndedPlayLocalExternalTuneEnded()
        }

        // to test playLocalTuneHasIvalidSourcePlayLocalExternalTuneInvalid
        should("test playLocalTuneHasIvalidSourcePlayLocalExternalTuneInvalid") {
            // uncomment below to test playLocalTuneHasIvalidSourcePlayLocalExternalTuneInvalid
            //apiInstance.playLocalTuneHasIvalidSourcePlayLocalExternalTuneInvalid()
        }

    }
}
