/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.SearchApi
import io.crates.api.models.CrateBasicPresentationBean
import io.crates.api.models.LuceneSearchResultInAllItems
import io.crates.api.models.LuceneSearchableAttributePresentationBean
import io.crates.api.models.TunePresentationBeanImpl

class SearchApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchApi
        //val apiInstance = SearchApi()

        // to test searchGetAvailableEntitiesSearchEntities
        should("test searchGetAvailableEntitiesSearchEntities") {
            // uncomment below to test searchGetAvailableEntitiesSearchEntities
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.searchGetAvailableEntitiesSearchEntities()
            //result shouldBe ("TODO")
        }

        // to test searchGetAvailableSearchingAttributesSearchEntityTypeAttributes
        should("test searchGetAvailableSearchingAttributesSearchEntityTypeAttributes") {
            // uncomment below to test searchGetAvailableSearchingAttributesSearchEntityTypeAttributes
            //val entityType : kotlin.String = entityType_example // kotlin.String | the entity type
            //val includeHidden : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.collections.List<LuceneSearchableAttributePresentationBean> = apiInstance.searchGetAvailableSearchingAttributesSearchEntityTypeAttributes(entityType, includeHidden)
            //result shouldBe ("TODO")
        }

        // to test searchGetOperatorsByTypeSearchOperators
        should("test searchGetOperatorsByTypeSearchOperators") {
            // uncomment below to test searchGetOperatorsByTypeSearchOperators
            //apiInstance.searchGetOperatorsByTypeSearchOperators()
        }

        // to test searchGetTunesLookinInAllFieldsReturnBasicTuneSearchTunesBasic
        should("test searchGetTunesLookinInAllFieldsReturnBasicTuneSearchTunesBasic") {
            // uncomment below to test searchGetTunesLookinInAllFieldsReturnBasicTuneSearchTunesBasic
            //val query : kotlin.String = query_example // kotlin.String | the query to search for
            //val result : kotlin.collections.List<TunePresentationBeanImpl> = apiInstance.searchGetTunesLookinInAllFieldsReturnBasicTuneSearchTunesBasic(query)
            //result shouldBe ("TODO")
        }

        // to test searchOnlineSearchSearchOnlineQuery
        should("test searchOnlineSearchSearchOnlineQuery") {
            // uncomment below to test searchOnlineSearchSearchOnlineQuery
            //val query : kotlin.String = query_example // kotlin.String | The user's term to search across online services
            //val service : kotlin.String = service_example // kotlin.String | service
            //val resultTypes : kotlin.String = resultTypes_example // kotlin.String | Optional result types filter. Comma separated values: TUNE, RELEASE, PLAYLIST
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : kotlin.collections.List<kotlin.Any> = apiInstance.searchOnlineSearchSearchOnlineQuery(query, service, resultTypes, clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test searchSearchCratesSearchCrates
        should("test searchSearchCratesSearchCrates") {
            // uncomment below to test searchSearchCratesSearchCrates
            //val query : kotlin.String = query_example // kotlin.String | The query to search for
            //val filterNoImport : kotlin.Boolean = true // kotlin.Boolean | Filter out crates that cannot be imported (SMART/SEARCH crates)
            //val result : kotlin.collections.List<CrateBasicPresentationBean> = apiInstance.searchSearchCratesSearchCrates(query, filterNoImport)
            //result shouldBe ("TODO")
        }

        // to test searchSearchSearch
        should("test searchSearchSearch") {
            // uncomment below to test searchSearchSearch
            //val query : kotlin.String = query_example // kotlin.String | the query to search for
            //val clientID : kotlin.String = clientID_example // kotlin.String | The id of the client who requested the invocation of this service
            //val result : LuceneSearchResultInAllItems = apiInstance.searchSearchSearch(query, clientID)
            //result shouldBe ("TODO")
        }

        // to test searchSearchTunesSearchTunes
        should("test searchSearchTunesSearchTunes") {
            // uncomment below to test searchSearchTunesSearchTunes
            //val query : kotlin.String = query_example // kotlin.String | the query to search for
            //val result : kotlin.collections.List<TunePresentationBeanImpl> = apiInstance.searchSearchTunesSearchTunes(query)
            //result shouldBe ("TODO")
        }

    }
}
