/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.ServerEventsApi

class ServerEventsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServerEventsApi
        //val apiInstance = ServerEventsApi()

        // to test serverEventsGetServerSentStatusServerevents
        should("test serverEventsGetServerSentStatusServerevents") {
            // uncomment below to test serverEventsGetServerSentStatusServerevents
            //apiInstance.serverEventsGetServerSentStatusServerevents()
        }

    }
}
