/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.SoundcloudOldApi
import io.crates.api.models.SoundCloudAppTokenPresentationBean
import io.crates.api.models.SoundCloudUserStatusPresentationBean
import io.crates.api.models.TunePresentationBeanImpl

class SoundcloudOldApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SoundcloudOldApi
        //val apiInstance = SoundcloudOldApi()

        // to test soundcloudOldAddPlaylistsFromSoundCloudSoundcloudOldImportPlaylists
        should("test soundcloudOldAddPlaylistsFromSoundCloudSoundcloudOldImportPlaylists") {
            // uncomment below to test soundcloudOldAddPlaylistsFromSoundCloudSoundcloudOldImportPlaylists
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : kotlin.collections.List<TunePresentationBeanImpl> = apiInstance.soundcloudOldAddPlaylistsFromSoundCloudSoundcloudOldImportPlaylists(clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test soundcloudOldAddTunesFromSoundCloudSoundcloudOldImportTracks
        should("test soundcloudOldAddTunesFromSoundCloudSoundcloudOldImportTracks") {
            // uncomment below to test soundcloudOldAddTunesFromSoundCloudSoundcloudOldImportTracks
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : kotlin.collections.List<TunePresentationBeanImpl> = apiInstance.soundcloudOldAddTunesFromSoundCloudSoundcloudOldImportTracks(clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test soundcloudOldConnectToSoundCloudSoundcloudOldConnect
        should("test soundcloudOldConnectToSoundCloudSoundcloudOldConnect") {
            // uncomment below to test soundcloudOldConnectToSoundCloudSoundcloudOldConnect
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : SoundCloudUserStatusPresentationBean = apiInstance.soundcloudOldConnectToSoundCloudSoundcloudOldConnect(clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test soundcloudOldConnectToSoundCloudSoundcloudOldConnect1
        should("test soundcloudOldConnectToSoundCloudSoundcloudOldConnect1") {
            // uncomment below to test soundcloudOldConnectToSoundCloudSoundcloudOldConnect1
            //val body : kotlin.String = body_example // kotlin.String | 
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : SoundCloudUserStatusPresentationBean = apiInstance.soundcloudOldConnectToSoundCloudSoundcloudOldConnect1(body, clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test soundcloudOldGetAppTokenSoundcloudOldAppToken
        should("test soundcloudOldGetAppTokenSoundcloudOldAppToken") {
            // uncomment below to test soundcloudOldGetAppTokenSoundcloudOldAppToken
            //val result : SoundCloudAppTokenPresentationBean = apiInstance.soundcloudOldGetAppTokenSoundcloudOldAppToken()
            //result shouldBe ("TODO")
        }

        // to test soundcloudOldImportNewTracksSoundcloudOldImportNew
        should("test soundcloudOldImportNewTracksSoundcloudOldImportNew") {
            // uncomment below to test soundcloudOldImportNewTracksSoundcloudOldImportNew
            //val date : kotlin.String = date_example // kotlin.String | the date up to which the import will take place
            //apiInstance.soundcloudOldImportNewTracksSoundcloudOldImportNew(date)
        }

        // to test soundcloudOldParseCallbackSoundcloudOldCallback
        should("test soundcloudOldParseCallbackSoundcloudOldCallback") {
            // uncomment below to test soundcloudOldParseCallbackSoundcloudOldCallback
            //apiInstance.soundcloudOldParseCallbackSoundcloudOldCallback()
        }

        // to test soundcloudOldSetSoundCloudCredentialsSoundcloudOldUserToken
        should("test soundcloudOldSetSoundCloudCredentialsSoundcloudOldUserToken") {
            // uncomment below to test soundcloudOldSetSoundCloudCredentialsSoundcloudOldUserToken
            //val username : kotlin.String = username_example // kotlin.String | the username
            //val password : kotlin.String = password_example // kotlin.String | the password
            //val importlikes : kotlin.String = importlikes_example // kotlin.String | automatic import likes? (default false)
            //val importplaylists : kotlin.String = importplaylists_example // kotlin.String | automatic import playlists? (default false)
            //val result : kotlin.collections.List<TunePresentationBeanImpl> = apiInstance.soundcloudOldSetSoundCloudCredentialsSoundcloudOldUserToken(username, password, importlikes, importplaylists)
            //result shouldBe ("TODO")
        }

    }
}
