/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.SpotifyApi
import io.crates.api.models.AuthorizationConnectionInfo

class SpotifyApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpotifyApi
        //val apiInstance = SpotifyApi()

        // to test spotifyConnectSpotifyConnect
        should("test spotifyConnectSpotifyConnect") {
            // uncomment below to test spotifyConnectSpotifyConnect
            //val importCollection : kotlin.String = importCollection_example // kotlin.String | imports or not the spotify collection
            //val spotifyEmail : kotlin.String = spotifyEmail_example // kotlin.String | the user's email
            //val result : AuthorizationConnectionInfo = apiInstance.spotifyConnectSpotifyConnect(importCollection, spotifyEmail)
            //result shouldBe ("TODO")
        }

        // to test spotifyDisconnectSpotifyDisconnect
        should("test spotifyDisconnectSpotifyDisconnect") {
            // uncomment below to test spotifyDisconnectSpotifyDisconnect
            //val result : AuthorizationConnectionInfo = apiInstance.spotifyDisconnectSpotifyDisconnect()
            //result shouldBe ("TODO")
        }

        // to test spotifyGetConnectStatusSpotifyConnectStatus
        should("test spotifyGetConnectStatusSpotifyConnectStatus") {
            // uncomment below to test spotifyGetConnectStatusSpotifyConnectStatus
            //val result : AuthorizationConnectionInfo = apiInstance.spotifyGetConnectStatusSpotifyConnectStatus()
            //result shouldBe ("TODO")
        }

        // to test spotifyImportUserLibrarySpotifyImportLibrary
        should("test spotifyImportUserLibrarySpotifyImportLibrary") {
            // uncomment below to test spotifyImportUserLibrarySpotifyImportLibrary
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : kotlin.String = apiInstance.spotifyImportUserLibrarySpotifyImportLibrary(clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test spotifyReconnectSpotifyReconnect
        should("test spotifyReconnectSpotifyReconnect") {
            // uncomment below to test spotifyReconnectSpotifyReconnect
            //val result : AuthorizationConnectionInfo = apiInstance.spotifyReconnectSpotifyReconnect()
            //result shouldBe ("TODO")
        }

        // to test spotifyVerifySpotifyVerification
        should("test spotifyVerifySpotifyVerification") {
            // uncomment below to test spotifyVerifySpotifyVerification
            //val code : kotlin.String = code_example // kotlin.String | the code
            //apiInstance.spotifyVerifySpotifyVerification(code)
        }

    }
}
