/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.StreamApi

class StreamApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StreamApi
        //val apiInstance = StreamApi()

        // to test streamStreamFileStreamTuneID
        should("test streamStreamFileStreamTuneID") {
            // uncomment below to test streamStreamFileStreamTuneID
            //val tuneID : kotlin.String = tuneID_example // kotlin.String | the tuneID of the tune to stream over the network
            //val range : kotlin.String = range_example // kotlin.String | header param indicating the range to play
            //val xPlaybackProfile : kotlin.String = xPlaybackProfile_example // kotlin.String | optional playback profile for stream compatibility decisions
            //apiInstance.streamStreamFileStreamTuneID(tuneID, range, xPlaybackProfile)
        }

    }
}
