/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.TuneCollectionViewsApi
import io.crates.api.models.TuneCollectionViewPresentationBean

class TuneCollectionViewsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TuneCollectionViewsApi
        //val apiInstance = TuneCollectionViewsApi()

        // to test tuneCollectionViewsAddCratesToCollectionViewTuneCollectionViewsSetCollectionViewId
        should("test tuneCollectionViewsAddCratesToCollectionViewTuneCollectionViewsSetCollectionViewId") {
            // uncomment below to test tuneCollectionViewsAddCratesToCollectionViewTuneCollectionViewsSetCollectionViewId
            //val collectionViewId : kotlin.String = collectionViewId_example // kotlin.String | the id of the collection view
            //val body : kotlin.String = body_example // kotlin.String | 
            //val device : kotlin.String = device_example // kotlin.String | 
            //val result : TuneCollectionViewPresentationBean = apiInstance.tuneCollectionViewsAddCratesToCollectionViewTuneCollectionViewsSetCollectionViewId(collectionViewId, body, device)
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsDeleteCollectionViewTuneCollectionViewsId
        should("test tuneCollectionViewsDeleteCollectionViewTuneCollectionViewsId") {
            // uncomment below to test tuneCollectionViewsDeleteCollectionViewTuneCollectionViewsId
            //val id : kotlin.String = id_example // kotlin.String | the id of the collection view
            //apiInstance.tuneCollectionViewsDeleteCollectionViewTuneCollectionViewsId(id)
        }

        // to test tuneCollectionViewsEditCollectionViewOfCrateTuneCollectionViewsCratesCrateIdEdit
        should("test tuneCollectionViewsEditCollectionViewOfCrateTuneCollectionViewsCratesCrateIdEdit") {
            // uncomment below to test tuneCollectionViewsEditCollectionViewOfCrateTuneCollectionViewsCratesCrateIdEdit
            //val crateId : kotlin.String = crateId_example // kotlin.String | the id of crate
            //val body : kotlin.String = body_example // kotlin.String | 
            //val device : kotlin.String = device_example // kotlin.String | 
            //val result : TuneCollectionViewPresentationBean = apiInstance.tuneCollectionViewsEditCollectionViewOfCrateTuneCollectionViewsCratesCrateIdEdit(crateId, body, device)
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsGetCollectionViewTypesTuneCollectionViewsTypes
        should("test tuneCollectionViewsGetCollectionViewTypesTuneCollectionViewsTypes") {
            // uncomment below to test tuneCollectionViewsGetCollectionViewTypesTuneCollectionViewsTypes
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.tuneCollectionViewsGetCollectionViewTypesTuneCollectionViewsTypes()
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsGetCollectionViewsByCollectionViewIDTuneCollectionViewsCollectionViewId
        should("test tuneCollectionViewsGetCollectionViewsByCollectionViewIDTuneCollectionViewsCollectionViewId") {
            // uncomment below to test tuneCollectionViewsGetCollectionViewsByCollectionViewIDTuneCollectionViewsCollectionViewId
            //val id : kotlin.String = id_example // kotlin.String | the id of the model view
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.tuneCollectionViewsGetCollectionViewsByCollectionViewIDTuneCollectionViewsCollectionViewId(id)
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsGetCollectionViewsByIDTuneCollectionViewsId
        should("test tuneCollectionViewsGetCollectionViewsByIDTuneCollectionViewsId") {
            // uncomment below to test tuneCollectionViewsGetCollectionViewsByIDTuneCollectionViewsId
            //val id : kotlin.String = id_example // kotlin.String | the id of the model view
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.tuneCollectionViewsGetCollectionViewsByIDTuneCollectionViewsId(id)
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsGetCollectionViewsByNameTuneCollectionViewsQuery
        should("test tuneCollectionViewsGetCollectionViewsByNameTuneCollectionViewsQuery") {
            // uncomment below to test tuneCollectionViewsGetCollectionViewsByNameTuneCollectionViewsQuery
            //val name : kotlin.String = name_example // kotlin.String | the name of the collection view
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.tuneCollectionViewsGetCollectionViewsByNameTuneCollectionViewsQuery(name)
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsGetCollectionViewsTuneCollectionViews
        should("test tuneCollectionViewsGetCollectionViewsTuneCollectionViews") {
            // uncomment below to test tuneCollectionViewsGetCollectionViewsTuneCollectionViews
            //val saved : kotlin.Boolean = true // kotlin.Boolean | 
            //val result : kotlin.collections.List<TuneCollectionViewPresentationBean> = apiInstance.tuneCollectionViewsGetCollectionViewsTuneCollectionViews(saved)
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsGetTuneAttributesTuneCollectionViewsTuneAttributes
        should("test tuneCollectionViewsGetTuneAttributesTuneCollectionViewsTuneAttributes") {
            // uncomment below to test tuneCollectionViewsGetTuneAttributesTuneCollectionViewsTuneAttributes
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.tuneCollectionViewsGetTuneAttributesTuneCollectionViewsTuneAttributes()
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsInsertCollectionViewTuneCollectionViews
        should("test tuneCollectionViewsInsertCollectionViewTuneCollectionViews") {
            // uncomment below to test tuneCollectionViewsInsertCollectionViewTuneCollectionViews
            //val body : kotlin.String = body_example // kotlin.String | 
            //val result : TuneCollectionViewPresentationBean = apiInstance.tuneCollectionViewsInsertCollectionViewTuneCollectionViews(body)
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsRemoveCratesFromCollectionViewTuneCollectionViewsRemove
        should("test tuneCollectionViewsRemoveCratesFromCollectionViewTuneCollectionViewsRemove") {
            // uncomment below to test tuneCollectionViewsRemoveCratesFromCollectionViewTuneCollectionViewsRemove
            //val body : kotlin.String = body_example // kotlin.String | 
            //val device : kotlin.String = device_example // kotlin.String | 
            //apiInstance.tuneCollectionViewsRemoveCratesFromCollectionViewTuneCollectionViewsRemove(body, device)
        }

        // to test tuneCollectionViewsResetCollectionViewsToDefaultsTuneCollectionViewsReset
        should("test tuneCollectionViewsResetCollectionViewsToDefaultsTuneCollectionViewsReset") {
            // uncomment below to test tuneCollectionViewsResetCollectionViewsToDefaultsTuneCollectionViewsReset
            //val result : kotlin.String = apiInstance.tuneCollectionViewsResetCollectionViewsToDefaultsTuneCollectionViewsReset()
            //result shouldBe ("TODO")
        }

        // to test tuneCollectionViewsUpdateCollectionViewTuneCollectionViews
        should("test tuneCollectionViewsUpdateCollectionViewTuneCollectionViews") {
            // uncomment below to test tuneCollectionViewsUpdateCollectionViewTuneCollectionViews
            //val body : kotlin.String = body_example // kotlin.String | 
            //val result : TuneCollectionViewPresentationBean = apiInstance.tuneCollectionViewsUpdateCollectionViewTuneCollectionViews(body)
            //result shouldBe ("TODO")
        }

    }
}
