/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.UserConfigurationApi
import io.crates.api.models.ConfigurationSettings
import io.crates.api.models.CratesRootFolders
import io.crates.api.models.TuneCollectionViewPresentationBean
import io.crates.api.models.UpdateTunePreferences
import io.crates.api.models.UserConversionStatus

class UserConfigurationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserConfigurationApi
        //val apiInstance = UserConfigurationApi()

        // to test userConfigurationAddItunesPathUserConfigurationItunesLibrary
        should("test userConfigurationAddItunesPathUserConfigurationItunesLibrary") {
            // uncomment below to test userConfigurationAddItunesPathUserConfigurationItunesLibrary
            //val path : kotlin.String = path_example // kotlin.String | the absolute path of the watcher folder
            //apiInstance.userConfigurationAddItunesPathUserConfigurationItunesLibrary(path)
        }

        // to test userConfigurationAddNewWatcherFolderForCrateUserConfigurationWatchfolderAddCratesId
        should("test userConfigurationAddNewWatcherFolderForCrateUserConfigurationWatchfolderAddCratesId") {
            // uncomment below to test userConfigurationAddNewWatcherFolderForCrateUserConfigurationWatchfolderAddCratesId
            //val id : kotlin.String = id_example // kotlin.String | the id of the crate to become a watched crate
            //apiInstance.userConfigurationAddNewWatcherFolderForCrateUserConfigurationWatchfolderAddCratesId(id)
        }

        // to test userConfigurationAddNewWatcherFolderUserConfigurationAdd
        should("test userConfigurationAddNewWatcherFolderUserConfigurationAdd") {
            // uncomment below to test userConfigurationAddNewWatcherFolderUserConfigurationAdd
            //val path : kotlin.String = path_example // kotlin.String | the absolute path of the watcher folder
            //apiInstance.userConfigurationAddNewWatcherFolderUserConfigurationAdd(path)
        }

        // to test userConfigurationAddNewWatcherFolderUserConfigurationWatchfolderAdd
        should("test userConfigurationAddNewWatcherFolderUserConfigurationWatchfolderAdd") {
            // uncomment below to test userConfigurationAddNewWatcherFolderUserConfigurationWatchfolderAdd
            //val path : kotlin.String = path_example // kotlin.String | the absolute path of the watcher folder
            //apiInstance.userConfigurationAddNewWatcherFolderUserConfigurationWatchfolderAdd(path)
        }

        // to test userConfigurationChangeRefreshPolicyUserConfigurationRefreshPolicy
        should("test userConfigurationChangeRefreshPolicyUserConfigurationRefreshPolicy") {
            // uncomment below to test userConfigurationChangeRefreshPolicyUserConfigurationRefreshPolicy
            //val refreshPolicy : kotlin.String = refreshPolicy_example // kotlin.String | the refresh policy
            //val secs : kotlin.String = secs_example // kotlin.String | the number of secs for periodic scan
            //apiInstance.userConfigurationChangeRefreshPolicyUserConfigurationRefreshPolicy(refreshPolicy, secs)
        }

        // to test userConfigurationClearAllFoldersUserConfiguration
        should("test userConfigurationClearAllFoldersUserConfiguration") {
            // uncomment below to test userConfigurationClearAllFoldersUserConfiguration
            //apiInstance.userConfigurationClearAllFoldersUserConfiguration()
        }

        // to test userConfigurationCloudBackupNowUserConfigurationBackupCloudBackupNow
        should("test userConfigurationCloudBackupNowUserConfigurationBackupCloudBackupNow") {
            // uncomment below to test userConfigurationCloudBackupNowUserConfigurationBackupCloudBackupNow
            //apiInstance.userConfigurationCloudBackupNowUserConfigurationBackupCloudBackupNow()
        }

        // to test userConfigurationEditPatternForRenameActionUserConfigurationTuneNamingPattern
        should("test userConfigurationEditPatternForRenameActionUserConfigurationTuneNamingPattern") {
            // uncomment below to test userConfigurationEditPatternForRenameActionUserConfigurationTuneNamingPattern
            //val pattern : kotlin.String = pattern_example // kotlin.String | the pattern
            //val result : kotlin.String = apiInstance.userConfigurationEditPatternForRenameActionUserConfigurationTuneNamingPattern(pattern)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationEditReleaseNamingPatternUserConfigurationReleaseNamingPattern
        should("test userConfigurationEditReleaseNamingPatternUserConfigurationReleaseNamingPattern") {
            // uncomment below to test userConfigurationEditReleaseNamingPatternUserConfigurationReleaseNamingPattern
            //val pattern : kotlin.String = pattern_example // kotlin.String | the pattern
            //val result : kotlin.String = apiInstance.userConfigurationEditReleaseNamingPatternUserConfigurationReleaseNamingPattern(pattern)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationExportLibraryConfigurationTimeUnitsUserConfigurationLibraryExportTimeUnits
        should("test userConfigurationExportLibraryConfigurationTimeUnitsUserConfigurationLibraryExportTimeUnits") {
            // uncomment below to test userConfigurationExportLibraryConfigurationTimeUnitsUserConfigurationLibraryExportTimeUnits
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.userConfigurationExportLibraryConfigurationTimeUnitsUserConfigurationLibraryExportTimeUnits(authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationExportLibraryConfigurationUserConfigurationLibraryExport
        should("test userConfigurationExportLibraryConfigurationUserConfigurationLibraryExport") {
            // uncomment below to test userConfigurationExportLibraryConfigurationUserConfigurationLibraryExport
            //val path : kotlin.String = path_example // kotlin.String | the absolute path of the export the file
            //val timeunit : kotlin.String = timeunit_example // kotlin.String | time unit to periodicall export the file
            //val timevalue : kotlin.String = timevalue_example // kotlin.String | time period to periodicall export the file
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationExportLibraryConfigurationUserConfigurationLibraryExport(path, timeunit, timevalue, authorization)
        }

        // to test userConfigurationGetAllRootFoldersUserConfigurationRootFolders
        should("test userConfigurationGetAllRootFoldersUserConfigurationRootFolders") {
            // uncomment below to test userConfigurationGetAllRootFoldersUserConfigurationRootFolders
            //val result : CratesRootFolders = apiInstance.userConfigurationGetAllRootFoldersUserConfigurationRootFolders()
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetAvailableCodecsUserConfigurationCodecs
        should("test userConfigurationGetAvailableCodecsUserConfigurationCodecs") {
            // uncomment below to test userConfigurationGetAvailableCodecsUserConfigurationCodecs
            //val result : kotlin.String = apiInstance.userConfigurationGetAvailableCodecsUserConfigurationCodecs()
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetBackupFoldersUserConfigurationBackupFolders
        should("test userConfigurationGetBackupFoldersUserConfigurationBackupFolders") {
            // uncomment below to test userConfigurationGetBackupFoldersUserConfigurationBackupFolders
            //apiInstance.userConfigurationGetBackupFoldersUserConfigurationBackupFolders()
        }

        // to test userConfigurationGetBandcampBuyModalPlayedThresholdUserConfigurationBandcampBuyModalPlayedThreshold
        should("test userConfigurationGetBandcampBuyModalPlayedThresholdUserConfigurationBandcampBuyModalPlayedThreshold") {
            // uncomment below to test userConfigurationGetBandcampBuyModalPlayedThresholdUserConfigurationBandcampBuyModalPlayedThreshold
            //val result : kotlin.String = apiInstance.userConfigurationGetBandcampBuyModalPlayedThresholdUserConfigurationBandcampBuyModalPlayedThreshold()
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetCloudStorageProvidersUserConfigurationCloudStorageProviders
        should("test userConfigurationGetCloudStorageProvidersUserConfigurationCloudStorageProviders") {
            // uncomment below to test userConfigurationGetCloudStorageProvidersUserConfigurationCloudStorageProviders
            //apiInstance.userConfigurationGetCloudStorageProvidersUserConfigurationCloudStorageProviders()
        }

        // to test userConfigurationGetConversionStatusUserConfigurationConversionStatus
        should("test userConfigurationGetConversionStatusUserConfigurationConversionStatus") {
            // uncomment below to test userConfigurationGetConversionStatusUserConfigurationConversionStatus
            //val result : UserConversionStatus = apiInstance.userConfigurationGetConversionStatusUserConfigurationConversionStatus()
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetDefaultCollectionViewUserConfigurationDefaultCollectionView
        should("test userConfigurationGetDefaultCollectionViewUserConfigurationDefaultCollectionView") {
            // uncomment below to test userConfigurationGetDefaultCollectionViewUserConfigurationDefaultCollectionView
            //val type : kotlin.String = type_example // kotlin.String | the absolute path of the watcher folder
            //val result : TuneCollectionViewPresentationBean = apiInstance.userConfigurationGetDefaultCollectionViewUserConfigurationDefaultCollectionView(type)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetPatternForRenameActionUserConfigurationTuneNamingPattern
        should("test userConfigurationGetPatternForRenameActionUserConfigurationTuneNamingPattern") {
            // uncomment below to test userConfigurationGetPatternForRenameActionUserConfigurationTuneNamingPattern
            //val result : kotlin.String = apiInstance.userConfigurationGetPatternForRenameActionUserConfigurationTuneNamingPattern()
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetQRCodeImageForServerDiscoveryUserConfigurationServerDiscoveryQrCode
        should("test userConfigurationGetQRCodeImageForServerDiscoveryUserConfigurationServerDiscoveryQrCode") {
            // uncomment below to test userConfigurationGetQRCodeImageForServerDiscoveryUserConfigurationServerDiscoveryQrCode
            //apiInstance.userConfigurationGetQRCodeImageForServerDiscoveryUserConfigurationServerDiscoveryQrCode()
        }

        // to test userConfigurationGetReleaseNamingPatternUserConfigurationReleaseNamingPattern
        should("test userConfigurationGetReleaseNamingPatternUserConfigurationReleaseNamingPattern") {
            // uncomment below to test userConfigurationGetReleaseNamingPatternUserConfigurationReleaseNamingPattern
            //val result : kotlin.String = apiInstance.userConfigurationGetReleaseNamingPatternUserConfigurationReleaseNamingPattern()
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetUserConfigurationUserConfiguration
        should("test userConfigurationGetUserConfigurationUserConfiguration") {
            // uncomment below to test userConfigurationGetUserConfigurationUserConfiguration
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : ConfigurationSettings = apiInstance.userConfigurationGetUserConfigurationUserConfiguration(authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationGetUserInfoUserConfigurationUserInfo
        should("test userConfigurationGetUserInfoUserConfigurationUserInfo") {
            // uncomment below to test userConfigurationGetUserInfoUserConfigurationUserInfo
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationGetUserInfoUserConfigurationUserInfo(authorization)
        }

        // to test userConfigurationLogoutUserUserConfigurationUserInfoLogout
        should("test userConfigurationLogoutUserUserConfigurationUserInfoLogout") {
            // uncomment below to test userConfigurationLogoutUserUserConfigurationUserInfoLogout
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationLogoutUserUserConfigurationUserInfoLogout(authorization)
        }

        // to test userConfigurationOverrideCratesDateAddedWithItunesDateAddedUserConfigurationOverrideCratesDateCreatedWithItuneDateAdded
        should("test userConfigurationOverrideCratesDateAddedWithItunesDateAddedUserConfigurationOverrideCratesDateCreatedWithItuneDateAdded") {
            // uncomment below to test userConfigurationOverrideCratesDateAddedWithItunesDateAddedUserConfigurationOverrideCratesDateCreatedWithItuneDateAdded
            //val allow : kotlin.String = allow_example // kotlin.String | set true if you want the override crates datecreated with itunes date added one
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationOverrideCratesDateAddedWithItunesDateAddedUserConfigurationOverrideCratesDateCreatedWithItuneDateAdded(allow, authorization)
        }

        // to test userConfigurationRecordConversionEventUserConfigurationConversionEvents
        should("test userConfigurationRecordConversionEventUserConfigurationConversionEvents") {
            // uncomment below to test userConfigurationRecordConversionEventUserConfigurationConversionEvents
            //val body : kotlin.String = body_example // kotlin.String | 
            //val result : UserConversionStatus = apiInstance.userConfigurationRecordConversionEventUserConfigurationConversionEvents(body)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationRemoveFolderUserConfigurationWatchfolderRemove
        should("test userConfigurationRemoveFolderUserConfigurationWatchfolderRemove") {
            // uncomment below to test userConfigurationRemoveFolderUserConfigurationWatchfolderRemove
            //val path : kotlin.String = path_example // kotlin.String | the absolute path of the watcher folder to be removed
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationRemoveFolderUserConfigurationWatchfolderRemove(path, authorization)
        }

        // to test userConfigurationResetDefaultCollectionViewUserConfigurationDefaultCollectionViewReset
        should("test userConfigurationResetDefaultCollectionViewUserConfigurationDefaultCollectionViewReset") {
            // uncomment below to test userConfigurationResetDefaultCollectionViewUserConfigurationDefaultCollectionViewReset
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : TuneCollectionViewPresentationBean = apiInstance.userConfigurationResetDefaultCollectionViewUserConfigurationDefaultCollectionViewReset(authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetAllowNonMusicYoutubeVideosToBeImportedByDefaultUserConfigurationImportNonMusicYoutubeVideos
        should("test userConfigurationSetAllowNonMusicYoutubeVideosToBeImportedByDefaultUserConfigurationImportNonMusicYoutubeVideos") {
            // uncomment below to test userConfigurationSetAllowNonMusicYoutubeVideosToBeImportedByDefaultUserConfigurationImportNonMusicYoutubeVideos
            //val allow : kotlin.String = allow_example // kotlin.String | set true if you want the autoimport videos from youtube that are not music related
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationSetAllowNonMusicYoutubeVideosToBeImportedByDefaultUserConfigurationImportNonMusicYoutubeVideos(allow, authorization)
        }

        // to test userConfigurationSetAllowServerDiscoverabilityUserConfigurationServerDiscoverability
        should("test userConfigurationSetAllowServerDiscoverabilityUserConfigurationServerDiscoverability") {
            // uncomment below to test userConfigurationSetAllowServerDiscoverabilityUserConfigurationServerDiscoverability
            //val enable : kotlin.String = enable_example // kotlin.String | set true if you want the app to register itself in the local network
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationSetAllowServerDiscoverabilityUserConfigurationServerDiscoverability(enable, authorization)
        }

        // to test userConfigurationSetAutoFindAudioSourceUserConfigurationAutoFindAudiosource
        should("test userConfigurationSetAutoFindAudioSourceUserConfigurationAutoFindAudiosource") {
            // uncomment below to test userConfigurationSetAutoFindAudioSourceUserConfigurationAutoFindAudiosource
            //val enable : kotlin.String = enable_example // kotlin.String | enable
            //val priorityList : kotlin.String = priorityList_example // kotlin.String | priorityList
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.userConfigurationSetAutoFindAudioSourceUserConfigurationAutoFindAudiosource(enable, priorityList, authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetDJProfileUserConfigurationDjProfile
        should("test userConfigurationSetDJProfileUserConfigurationDjProfile") {
            // uncomment below to test userConfigurationSetDJProfileUserConfigurationDjProfile
            //val enable : kotlin.String = enable_example // kotlin.String | set true to enable
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationSetDJProfileUserConfigurationDjProfile(enable, authorization)
        }

        // to test userConfigurationSetForceUpdatesToID3TagUserConfigurationPersistsId3tag
        should("test userConfigurationSetForceUpdatesToID3TagUserConfigurationPersistsId3tag") {
            // uncomment below to test userConfigurationSetForceUpdatesToID3TagUserConfigurationPersistsId3tag
            //val force : kotlin.String = force_example // kotlin.String | whether or not it should write changes to id3tags. expects true/false
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : UpdateTunePreferences = apiInstance.userConfigurationSetForceUpdatesToID3TagUserConfigurationPersistsId3tag(force, authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetGDriveConvertAudioFilesBeforeUploadingUserConfigurationSetGDriveConvertAudioFilesBeforeUploading
        should("test userConfigurationSetGDriveConvertAudioFilesBeforeUploadingUserConfigurationSetGDriveConvertAudioFilesBeforeUploading") {
            // uncomment below to test userConfigurationSetGDriveConvertAudioFilesBeforeUploadingUserConfigurationSetGDriveConvertAudioFilesBeforeUploading
            //val enable : kotlin.String = enable_example // kotlin.String | when uploading to google drive, if this setting is on, it will convert the file first according to the default conversion profile
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.userConfigurationSetGDriveConvertAudioFilesBeforeUploadingUserConfigurationSetGDriveConvertAudioFilesBeforeUploading(enable, authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetImportBandcampTagsEnabledUserConfigurationSetImportBandcampTagsEnabled
        should("test userConfigurationSetImportBandcampTagsEnabledUserConfigurationSetImportBandcampTagsEnabled") {
            // uncomment below to test userConfigurationSetImportBandcampTagsEnabledUserConfigurationSetImportBandcampTagsEnabled
            //val enable : kotlin.String = enable_example // kotlin.String | When importing a tune or release from bandcamp, if this is true, it will get keywords from bandcamp and add as tags on Tune
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.userConfigurationSetImportBandcampTagsEnabledUserConfigurationSetImportBandcampTagsEnabled(enable, authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetImportDiscogsCollectionByDefaultUserConfigurationDefaultImportDiscogsCollection
        should("test userConfigurationSetImportDiscogsCollectionByDefaultUserConfigurationDefaultImportDiscogsCollection") {
            // uncomment below to test userConfigurationSetImportDiscogsCollectionByDefaultUserConfigurationDefaultImportDiscogsCollection
            //val enable : kotlin.String = enable_example // kotlin.String | set true if you want the app to import discogs collection by default when firstly connects
            //apiInstance.userConfigurationSetImportDiscogsCollectionByDefaultUserConfigurationDefaultImportDiscogsCollection(enable)
        }

        // to test userConfigurationSetImportDiscogsWantlistOnConnectUserConfigurationDefaultImportDiscogsWantlist
        should("test userConfigurationSetImportDiscogsWantlistOnConnectUserConfigurationDefaultImportDiscogsWantlist") {
            // uncomment below to test userConfigurationSetImportDiscogsWantlistOnConnectUserConfigurationDefaultImportDiscogsWantlist
            //val enable : kotlin.String = enable_example // kotlin.String | set true if you want the app to import discogs collection by default when firstly connects
            //apiInstance.userConfigurationSetImportDiscogsWantlistOnConnectUserConfigurationDefaultImportDiscogsWantlist(enable)
        }

        // to test userConfigurationSetMobileDownloadAutoConversionProfileUserConfigurationMobileDownloadAutoConversionProfile
        should("test userConfigurationSetMobileDownloadAutoConversionProfileUserConfigurationMobileDownloadAutoConversionProfile") {
            // uncomment below to test userConfigurationSetMobileDownloadAutoConversionProfileUserConfigurationMobileDownloadAutoConversionProfile
            //val conversionProfileId : kotlin.String = conversionProfileId_example // kotlin.String | When returning a stream to mobile clients, automatically select or convert to the required format according to this conversion Profile
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : kotlin.String = apiInstance.userConfigurationSetMobileDownloadAutoConversionProfileUserConfigurationMobileDownloadAutoConversionProfile(conversionProfileId, authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetRootFoldersUserConfigurationRootFolders
        should("test userConfigurationSetRootFoldersUserConfigurationRootFolders") {
            // uncomment below to test userConfigurationSetRootFoldersUserConfigurationRootFolders
            //val body : kotlin.String = body_example // kotlin.String | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : CratesRootFolders = apiInstance.userConfigurationSetRootFoldersUserConfigurationRootFolders(body, authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetTuneMatcherEnableUserConfigurationEnableMatcher
        should("test userConfigurationSetTuneMatcherEnableUserConfigurationEnableMatcher") {
            // uncomment below to test userConfigurationSetTuneMatcherEnableUserConfigurationEnableMatcher
            //val enable : kotlin.String = enable_example // kotlin.String | set true if you want the app to turn on the tune's matcher
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationSetTuneMatcherEnableUserConfigurationEnableMatcher(enable, authorization)
        }

        // to test userConfigurationSetUserConfigurationUserConfiguration
        should("test userConfigurationSetUserConfigurationUserConfiguration") {
            // uncomment below to test userConfigurationSetUserConfigurationUserConfiguration
            //val body : kotlin.String = body_example // kotlin.String | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : ConfigurationSettings = apiInstance.userConfigurationSetUserConfigurationUserConfiguration(body, authorization)
            //result shouldBe ("TODO")
        }

        // to test userConfigurationSetUserInfoUserConfigurationUserInfo
        should("test userConfigurationSetUserInfoUserConfigurationUserInfo") {
            // uncomment below to test userConfigurationSetUserInfoUserConfigurationUserInfo
            //val body : kotlin.String = body_example // kotlin.String | 
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //apiInstance.userConfigurationSetUserInfoUserConfigurationUserInfo(body, authorization)
        }

        // to test userConfigurationUpdateUserConfigurationUserConfiguration
        should("test userConfigurationUpdateUserConfigurationUserConfiguration") {
            // uncomment below to test userConfigurationUpdateUserConfigurationUserConfiguration
            //val authorization : kotlin.String = authorization_example // kotlin.String | 
            //val result : ConfigurationSettings = apiInstance.userConfigurationUpdateUserConfigurationUserConfiguration(authorization)
            //result shouldBe ("TODO")
        }

    }
}
