/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.apis.WaveformApi
import io.crates.api.models.WaveformPresentationBean

class WaveformApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WaveformApi
        //val apiInstance = WaveformApi()

        // to test waveformGetAvailableWaveformTypesWaveformTypes
        should("test waveformGetAvailableWaveformTypesWaveformTypes") {
            // uncomment below to test waveformGetAvailableWaveformTypesWaveformTypes
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.waveformGetAvailableWaveformTypesWaveformTypes()
            //result shouldBe ("TODO")
        }

        // to test waveformGetSupportedAudiosourceTypesWaveformAudiosources
        should("test waveformGetSupportedAudiosourceTypesWaveformAudiosources") {
            // uncomment below to test waveformGetSupportedAudiosourceTypesWaveformAudiosources
            //val result : kotlin.collections.List<kotlin.String> = apiInstance.waveformGetSupportedAudiosourceTypesWaveformAudiosources()
            //result shouldBe ("TODO")
        }

        // to test waveformGetWaveformFromAudioSourceWaveformAudiosourceAudiosourceId
        should("test waveformGetWaveformFromAudioSourceWaveformAudiosourceAudiosourceId") {
            // uncomment below to test waveformGetWaveformFromAudioSourceWaveformAudiosourceAudiosourceId
            //val audiosourceId : kotlin.String = audiosourceId_example // kotlin.String | 
            //val tuneId : kotlin.String = tuneId_example // kotlin.String | id of the audiosource
            //val type : kotlin.String = type_example // kotlin.String | the precision of the point's value of the waveform. For 100 digits it expects the value: 100 (default is 6 digits)
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : WaveformPresentationBean = apiInstance.waveformGetWaveformFromAudioSourceWaveformAudiosourceAudiosourceId(audiosourceId, tuneId, type, clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test waveformGetWaveformFromTuneWaveformTunesTuneId
        should("test waveformGetWaveformFromTuneWaveformTunesTuneId") {
            // uncomment below to test waveformGetWaveformFromTuneWaveformTunesTuneId
            //val tuneId : kotlin.String = tuneId_example // kotlin.String | id of the tune
            //val clientID : kotlin.String = clientID_example // kotlin.String | 
            //val callbacks : kotlin.String = callbacks_example // kotlin.String | The flag to indicate whether or not to send callback via websocket. Allow type: 'CALLBACKS_OFF' and 'CALLBACKS_ON'
            //val result : WaveformPresentationBean = apiInstance.waveformGetWaveformFromTuneWaveformTunesTuneId(tuneId, clientID, callbacks)
            //result shouldBe ("TODO")
        }

        // to test waveformTestProducedWaveformWaveformTestWidthWidth
        should("test waveformTestProducedWaveformWaveformTestWidthWidth") {
            // uncomment below to test waveformTestProducedWaveformWaveformTestWidthWidth
            //val width : kotlin.String = width_example // kotlin.String | the max width of the waveform (default is 500px)
            //val path : kotlin.String = path_example // kotlin.String | path of a wav file
            //val precision : kotlin.String = precision_example // kotlin.String | the precision of the point's value of the waveform. For 100 digits it expects the value: 100 (default is 6 digits)
            //val result : WaveformPresentationBean = apiInstance.waveformTestProducedWaveformWaveformTestWidthWidth(width, path, precision)
            //result shouldBe ("TODO")
        }

    }
}
