/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.LinkURL

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the Artist object
 *
 * @param artistID the artists's ID
 * @param name the artists's name
 * @param realName the artists's realName
 * @param profile the artists's profile
 * @param artistUrl the artists's url
 * @param discogsID the artists's discogsID
 * @param discogsURL the artists's discogsURL
 * @param location the artists's location
 * @param thumbImageID the label's thumbImageID
 * @param imageIDs the artists's images
 * @param linkURLs the artists's links
 * @param sourceURLs the artists's sourceURLs
 * @param sources the artists's sources
 */
@Serializable

public data class ArtistPresentationBean (

    /* the artists's ID */
    @SerialName(value = "artistID")
    val artistID: kotlin.Long? = null,

    /* the artists's name */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* the artists's realName */
    @SerialName(value = "realName")
    val realName: kotlin.String? = null,

    /* the artists's profile */
    @SerialName(value = "profile")
    val profile: kotlin.String? = null,

    /* the artists's url */
    @SerialName(value = "artistUrl")
    val artistUrl: kotlin.String? = null,

    /* the artists's discogsID */
    @SerialName(value = "discogsID")
    val discogsID: kotlin.Int? = null,

    /* the artists's discogsURL */
    @SerialName(value = "discogsURL")
    val discogsURL: kotlin.String? = null,

    /* the artists's location */
    @SerialName(value = "location")
    val location: kotlin.String? = null,

    /* the label's thumbImageID */
    @SerialName(value = "thumbImageID")
    val thumbImageID: kotlin.Long? = null,

    /* the artists's images */
    @SerialName(value = "imageIDs")
    val imageIDs: kotlin.collections.List<kotlin.Long>? = null,

    /* the artists's links */
    @SerialName(value = "linkURLs")
    val linkURLs: kotlin.collections.List<LinkURL>? = null,

    /* the artists's sourceURLs */
    @SerialName(value = "sourceURLs")
    val sourceURLs: kotlin.collections.List<kotlin.String>? = null,

    /* the artists's sources */
    @SerialName(value = "sources")
    val sources: kotlin.collections.List<LinkURL>? = null

) {


}

