/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the crate type object
 *
 * @param typeID the audio source type's ID
 * @param typeName the audio source type's name
 */
@Serializable

public data class AudioSourceTypePresentationBean (

    /* the audio source type's ID */
    @SerialName(value = "typeID")
    val typeID: kotlin.Long,

    /* the audio source type's name */
    @SerialName(value = "typeName")
    val typeName: kotlin.String

) {


}

