/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents an audio source
 *
 * @param objectID the id of the corresponding object
 * @param source the source of the audio
 * @param name the name of the audio source 
 * @param location the location
 * @param defaultAudioSourceType the default audio source type ID
 * @param bitRate the bitRate
 * @param bpm the bpm
 * @param codec the codec
 * @param length the length
 * @param sampleRate the sampleRate
 * @param status the status
 * @param dateAdded the date Added
 * @param defaultAudioSource the date Added
 * @param pageUrl the page url
 * @param fileSize file size
 * @param bitDepth bit depth
 */
@Serializable

public data class AudioSourcePresentationImpl (

    /* the id of the corresponding object */
    @SerialName(value = "objectID")
    val objectID: kotlin.Long,

    /* the source of the audio */
    @SerialName(value = "source")
    val source: kotlin.String,

    /* the name of the audio source  */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* the location */
    @SerialName(value = "location")
    val location: kotlin.String,

    /* the default audio source type ID */
    @SerialName(value = "defaultAudioSourceType")
    val defaultAudioSourceType: kotlin.Long,

    /* the bitRate */
    @SerialName(value = "bitRate")
    val bitRate: kotlin.String? = null,

    /* the bpm */
    @SerialName(value = "bpm")
    val bpm: kotlin.String? = null,

    /* the codec */
    @SerialName(value = "codec")
    val codec: kotlin.String? = null,

    /* the length */
    @SerialName(value = "length")
    val length: kotlin.String? = null,

    /* the sampleRate */
    @SerialName(value = "sampleRate")
    val sampleRate: kotlin.String? = null,

    /* the status */
    @SerialName(value = "status")
    val status: kotlin.String? = null,

    /* the date Added */
    @SerialName(value = "dateAdded")
    val dateAdded: kotlin.String? = null,

    /* the date Added */
    @SerialName(value = "defaultAudioSource")
    val defaultAudioSource: kotlin.Boolean? = null,

    /* the page url */
    @SerialName(value = "pageUrl")
    val pageUrl: kotlin.String? = null,

    /* file size */
    @SerialName(value = "fileSize")
    val fileSize: kotlin.String? = null,

    /* bit depth */
    @SerialName(value = "bitDepth")
    val bitDepth: kotlin.String? = null

) {


}

