/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.CodecPreferenceElement

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The list of the supported codecs with their preferences to play
 *
 * @param codecPreferences The list of the supported codecs with their preferences to play
 */
@Serializable

public data class CodecPreferences (

    /* The list of the supported codecs with their preferences to play */
    @SerialName(value = "codecPreferences")
    val codecPreferences: kotlin.collections.List<CodecPreferenceElement>

) {


}

