/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param daysSinceFirstUse Days since the first run of the app
 * @param tuneCount Total number of tunes in the library
 * @param importedSourceCount Number of distinct imported source families
 * @param importedSources Distinct imported source families
 */
@Serializable

public data class ConversionMetrics (

    /* Days since the first run of the app */
    @SerialName(value = "daysSinceFirstUse")
    val daysSinceFirstUse: kotlin.Int? = null,

    /* Total number of tunes in the library */
    @SerialName(value = "tuneCount")
    val tuneCount: kotlin.Int? = null,

    /* Number of distinct imported source families */
    @SerialName(value = "importedSourceCount")
    val importedSourceCount: kotlin.Int? = null,

    /* Distinct imported source families */
    @SerialName(value = "importedSources")
    val importedSources: kotlin.collections.List<kotlin.String>? = null

) {


}

