/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param enableGems 
 * @param syncGemsOnStartup 
 * @param lastProcessedBlocks 
 * @param notificationHistory 
 * @param lastHighlightSentAt 
 * @param statsInitialSyncDone 
 * @param notificationsEnabled 
 */
@Serializable

public data class GemsFeedbackSettings (

    @SerialName(value = "enableGems")
    val enableGems: kotlin.Boolean? = null,

    @SerialName(value = "syncGemsOnStartup")
    val syncGemsOnStartup: kotlin.Boolean? = null,

    @SerialName(value = "lastProcessedBlocks")
    val lastProcessedBlocks: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    @SerialName(value = "notificationHistory")
    val notificationHistory: kotlin.collections.Map<kotlin.String, kotlin.Long>? = null,

    @SerialName(value = "lastHighlightSentAt")
    val lastHighlightSentAt: kotlin.Long? = null,

    @SerialName(value = "statsInitialSyncDone")
    val statsInitialSyncDone: kotlin.Boolean? = null,

    @SerialName(value = "notificationsEnabled")
    val notificationsEnabled: kotlin.Boolean? = null

) {


}

