/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.GemStat
import io.crates.api.models.Highlight

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param gemsPosted 
 * @param revealsReceived 
 * @param gemsDiscovered 
 * @param downvotesReceived 
 * @param passesReceived 
 * @param revealCounts 
 * @param highlightCandidates 
 * @param topRevealStats 
 * @param gemsDiscoveredTopRevealStats 
 * @param gemsDiscoveredRevealCounts 
 * @param ownerRevealCounts 
 * @param ownerDownvoteCounts 
 * @param ownerPassCounts 
 * @param startBlock 
 * @param endBlock 
 * @param startTimestampMillis 
 * @param endTimestampMillis 
 */
@Serializable

public data class GemsFeedbackStatsPresentation (

    @SerialName(value = "gemsPosted")
    val gemsPosted: kotlin.Int? = null,

    @SerialName(value = "revealsReceived")
    val revealsReceived: kotlin.Int? = null,

    @SerialName(value = "gemsDiscovered")
    val gemsDiscovered: kotlin.Int? = null,

    @SerialName(value = "downvotesReceived")
    val downvotesReceived: kotlin.Int? = null,

    @SerialName(value = "passesReceived")
    val passesReceived: kotlin.Int? = null,

    @SerialName(value = "revealCounts")
    val revealCounts: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @SerialName(value = "highlightCandidates")
    val highlightCandidates: kotlin.collections.List<Highlight>? = null,

    @SerialName(value = "topRevealStats")
    val topRevealStats: kotlin.collections.List<GemStat>? = null,

    @SerialName(value = "gemsDiscoveredTopRevealStats")
    val gemsDiscoveredTopRevealStats: kotlin.collections.List<GemStat>? = null,

    @SerialName(value = "gemsDiscoveredRevealCounts")
    val gemsDiscoveredRevealCounts: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @SerialName(value = "ownerRevealCounts")
    val ownerRevealCounts: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @SerialName(value = "ownerDownvoteCounts")
    val ownerDownvoteCounts: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @SerialName(value = "ownerPassCounts")
    val ownerPassCounts: kotlin.collections.Map<kotlin.String, kotlin.Int>? = null,

    @SerialName(value = "startBlock")
    val startBlock: kotlin.Int? = null,

    @SerialName(value = "endBlock")
    val endBlock: kotlin.Int? = null,

    @SerialName(value = "startTimestampMillis")
    val startTimestampMillis: kotlin.Long? = null,

    @SerialName(value = "endTimestampMillis")
    val endTimestampMillis: kotlin.Long? = null

) {


}

