/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param entityStatus Unresolved: BaseObjectStatus
 * @param interestID 
 * @param dateAdded 
 * @param type 
 * @param interestValue 
 * @param discogsID 
 * @param explicitImport 
 * @param allowReImport 
 */
@Serializable

public data class InterestBO (

    /* Unresolved: BaseObjectStatus */
    @Contextual @SerialName(value = "entityStatus")
    val entityStatus: kotlin.Any? = null,

    @SerialName(value = "interestID")
    val interestID: kotlin.Long? = null,

    @Contextual @SerialName(value = "dateAdded")
    val dateAdded: kotlin.time.Instant? = null,

    @SerialName(value = "type")
    val type: kotlin.String? = null,

    @SerialName(value = "interestValue")
    val interestValue: kotlin.String? = null,

    @SerialName(value = "discogsID")
    val discogsID: kotlin.Int? = null,

    @SerialName(value = "explicitImport")
    val explicitImport: kotlin.Boolean? = null,

    @SerialName(value = "allowReImport")
    val allowReImport: kotlin.Boolean? = null

) {


}

