/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.InterestAbstractImpl

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the label interest object
 *
 * @param interestID the interests's ID
 * @param dateAdded the interests's dateAdded
 * @param type the interests's type
 * @param `value` the interests's value
 * @param discogsID the interests's discogsID
 * @param explicitImport the interests's indication whether or not is from explicit reimport
 * @param allowReImport the interests's indication whether or not explicitly allows reimport
 * @param interestAbstractImpl 
 */
@Serializable

public data class InterestLabelPresentationBean (

    /* the interests's ID */
    @SerialName(value = "interestID")
    val interestID: kotlin.Long? = null,

    /* the interests's dateAdded */
    @Contextual @SerialName(value = "dateAdded")
    val dateAdded: kotlin.time.Instant? = null,

    /* the interests's type */
    @SerialName(value = "type")
    val type: kotlin.String? = null,

    /* the interests's value */
    @SerialName(value = "value")
    val `value`: kotlin.String? = null,

    /* the interests's discogsID */
    @SerialName(value = "discogsID")
    val discogsID: kotlin.Int? = null,

    /* the interests's indication whether or not is from explicit reimport */
    @SerialName(value = "explicitImport")
    val explicitImport: kotlin.Boolean? = null,

    /* the interests's indication whether or not explicitly allows reimport */
    @SerialName(value = "allowReImport")
    val allowReImport: kotlin.Boolean? = null,

    @SerialName(value = "interestAbstractImpl")
    val interestAbstractImpl: InterestAbstractImpl? = null

) {


}

