/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.LinkURL

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the Label object
 *
 * @param labelID the label's ID
 * @param name the label's name
 * @param profile the label's profile
 * @param location the artists's location
 * @param contactInfo the label's contactInfo
 * @param url the label's url
 * @param discogsID the label's discogsID
 * @param discogsUrl the label's discogsUrl
 * @param thumbImageID the label's thumbImageID
 * @param imageIDs 
 * @param linkURLs the label's links
 * @param sources the label's sources
 */
@Serializable

public data class LabelPresentationBean (

    /* the label's ID */
    @SerialName(value = "labelID")
    val labelID: kotlin.Long? = null,

    /* the label's name */
    @SerialName(value = "name")
    val name: kotlin.String? = null,

    /* the label's profile */
    @SerialName(value = "profile")
    val profile: kotlin.String? = null,

    /* the artists's location */
    @SerialName(value = "location")
    val location: kotlin.String? = null,

    /* the label's contactInfo */
    @SerialName(value = "contactInfo")
    val contactInfo: kotlin.String? = null,

    /* the label's url */
    @SerialName(value = "url")
    val url: kotlin.String? = null,

    /* the label's discogsID */
    @SerialName(value = "discogsID")
    val discogsID: kotlin.Int? = null,

    /* the label's discogsUrl */
    @SerialName(value = "discogsUrl")
    val discogsUrl: kotlin.String? = null,

    /* the label's thumbImageID */
    @SerialName(value = "thumbImageID")
    val thumbImageID: kotlin.Long? = null,

    @SerialName(value = "imageIDs")
    val imageIDs: kotlin.collections.List<kotlin.Long>? = null,

    /* the label's links */
    @SerialName(value = "linkURLs")
    val linkURLs: kotlin.collections.List<LinkURL>? = null,

    /* the label's sources */
    @SerialName(value = "sources")
    val sources: kotlin.collections.List<LinkURL>? = null

) {


}

