/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This class represents a UserInfo data transfer object
 *
 * @param userId user_id
 * @param userEmail user_email
 * @param userFirstName user_first_name
 * @param userLastName user_last_name
 * @param userNickname user_nickname
 * @param userDisplayName user_display_name
 * @param avatarUrl avatar_url
 */
@Serializable

public data class LookupUserDetails (

    /* user_id */
    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    /* user_email */
    @SerialName(value = "userEmail")
    val userEmail: kotlin.String? = null,

    /* user_first_name */
    @SerialName(value = "userFirstName")
    val userFirstName: kotlin.String? = null,

    /* user_last_name */
    @SerialName(value = "userLastName")
    val userLastName: kotlin.String? = null,

    /* user_nickname */
    @SerialName(value = "userNickname")
    val userNickname: kotlin.String? = null,

    /* user_display_name */
    @SerialName(value = "userDisplayName")
    val userDisplayName: kotlin.String? = null,

    /* avatar_url */
    @SerialName(value = "avatarUrl")
    val avatarUrl: kotlin.String? = null

) {


}

