/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.CrateBasicPresentationBean

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the lucene result while searching on everything (tunes and crates)
 *
 * @param crates list of crates
 * @param tunes list of tunes
 */
@Serializable

public data class LuceneSearchResultInAllItems (

    /* list of crates */
    @SerialName(value = "crates")
    val crates: kotlin.collections.List<CrateBasicPresentationBean>,

    /* list of tunes */
    @SerialName(value = "tunes")
    val tunes: kotlin.collections.List<@Contextual kotlin.Any>

) {


}

