/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the lucene searchable attributes for an entity
 *
 * @param attributeName the attribute's name
 * @param displayName the attribute's display name
 * @param tableName the table where the attribute belongs to
 * @param columnType Unresolved: CratesColumnType
 * @param isCratesColumnSearchableByDefault Unresolved: IsCratesColumnSearchableByDefault
 * @param displayToUser whether or not this attribute will be displayed to the user
 */
@Serializable

public data class LuceneSearchableAttributePresentationBean (

    /* the attribute's name */
    @SerialName(value = "attributeName")
    val attributeName: kotlin.String? = null,

    /* the attribute's display name */
    @SerialName(value = "displayName")
    val displayName: kotlin.String? = null,

    /* the table where the attribute belongs to */
    @SerialName(value = "tableName")
    val tableName: kotlin.String? = null,

    /* Unresolved: CratesColumnType */
    @Contextual @SerialName(value = "columnType")
    val columnType: kotlin.Any? = null,

    /* Unresolved: IsCratesColumnSearchableByDefault */
    @Contextual @SerialName(value = "isCratesColumnSearchableByDefault")
    val isCratesColumnSearchableByDefault: kotlin.Any? = null,

    /* whether or not this attribute will be displayed to the user */
    @SerialName(value = "displayToUser")
    val displayToUser: kotlin.Boolean? = null

) {


}

