/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * One of the recently used paths to move tunes, indicating if this was the last one used
 *
 * @param path the path
 * @param lastUsed indicating whether this was the last one used
 */
@Serializable

public data class MoveToPathRecentlyUsedPathsElement (

    /* the path */
    @SerialName(value = "path")
    val path: kotlin.String,

    /* indicating whether this was the last one used */
    @SerialName(value = "lastUsed")
    val lastUsed: kotlin.Boolean

) {


}

