/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.TunePresentationBeanImpl

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the previous context of the CrateQueueController
 *
 * @param activeCrateID the last active crate id
 * @param currentTune 
 * @param tuneOrderedID the ordering of the tune in the crate
 * @param currentLocationInMilis the position in which the tune was playing
 * @param playQueueRepeatPolicy Unresolved: PlayQueueRepeatPolicy
 * @param playQueueShufflePolicy Unresolved: PlayQueueShufflePolicy
 * @param playQueueControllerPlayerStatus Unresolved: PlayerManagerPlayerStatus
 * @param volumeLevel the volume of the player
 */
@Serializable

public data class PlayQueuePreviousContext (

    /* the last active crate id */
    @SerialName(value = "activeCrateID")
    val activeCrateID: kotlin.Long,

    @SerialName(value = "currentTune")
    val currentTune: TunePresentationBeanImpl,

    /* the ordering of the tune in the crate */
    @SerialName(value = "tuneOrderedID")
    val tuneOrderedID: kotlin.Int,

    /* the position in which the tune was playing */
    @SerialName(value = "currentLocationInMilis")
    val currentLocationInMilis: kotlin.Long,

    /* Unresolved: PlayQueueRepeatPolicy */
    @Contextual @SerialName(value = "playQueueRepeatPolicy")
    val playQueueRepeatPolicy: kotlin.Any,

    /* Unresolved: PlayQueueShufflePolicy */
    @Contextual @SerialName(value = "playQueueShufflePolicy")
    val playQueueShufflePolicy: kotlin.Any,

    /* Unresolved: PlayerManagerPlayerStatus */
    @Contextual @SerialName(value = "playQueueControllerPlayerStatus")
    val playQueueControllerPlayerStatus: kotlin.Any,

    /* the volume of the player */
    @SerialName(value = "volumeLevel")
    val volumeLevel: kotlin.Float? = null

) {


}

