/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.AudioSourceDTO
import io.crates.api.models.BuyLinkDTO
import io.crates.api.models.ContributorDTO
import io.crates.api.models.PlaylistTuneDTO
import io.crates.api.models.TimestampedCommentDTO

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param position 
 * @param tune 
 * @param comment 
 * @param contributor 
 * @param timestampedComments 
 * @param audioSources 
 * @param buyLinks 
 */
@Serializable

public data class PlaylistTrackDTO (

    @SerialName(value = "position")
    val position: kotlin.Int? = null,

    @SerialName(value = "tune")
    val tune: PlaylistTuneDTO? = null,

    @SerialName(value = "comment")
    val comment: kotlin.String? = null,

    @SerialName(value = "contributor")
    val contributor: ContributorDTO? = null,

    @SerialName(value = "timestampedComments")
    val timestampedComments: kotlin.collections.List<TimestampedCommentDTO>? = null,

    @SerialName(value = "audioSources")
    val audioSources: kotlin.collections.List<AudioSourceDTO>? = null,

    @SerialName(value = "buyLinks")
    val buyLinks: kotlin.collections.List<BuyLinkDTO>? = null

) {


}

