/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param releaseID 
 * @param name 
 * @param crateID 
 */
@Serializable

public data class ReleaseSimplePresentationBean (

    @SerialName(value = "releaseID")
    val releaseID: kotlin.Long? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "crateID")
    val crateID: kotlin.Long? = null

) {


}

