/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the application's specific tokens for accessing SoundCloud's API
 *
 * @param appID the application's id
 * @param appSecret the application's secret
 */
@Serializable

public data class SoundCloudAppTokenPresentationBean (

    /* the application's id */
    @SerialName(value = "appID")
    val appID: kotlin.String,

    /* the application's secret */
    @SerialName(value = "appSecret")
    val appSecret: kotlin.String

) {


}

