/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the parameter needed for (un)subscribing to events
 *
 * @param eventName The name of the event to subscribe
 * @param clientID the credentials of the client
 * @param outputMode Unresolved: SubscriptionTypeOutputMode
 */
@Serializable

public data class SubscriptionType (

    /* The name of the event to subscribe */
    @SerialName(value = "eventName")
    val eventName: kotlin.String,

    /* the credentials of the client */
    @SerialName(value = "clientID")
    val clientID: kotlin.String,

    /* Unresolved: SubscriptionTypeOutputMode */
    @Contextual @SerialName(value = "outputMode")
    val outputMode: kotlin.Any

) {


}

