/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents a tab's attributes
 *
 * @param name the name of the crate
 * @param crateID the id of the crate
 * @param ordering the ordering in the tab panel
 * @param icon the icon name
 * @param removed indicates if the tabs has been removed from the user
 * @param crateExists indicates whether the crate exists in the system
 */
@Serializable

public data class TabCratesSettingsElement (

    /* the name of the crate */
    @SerialName(value = "name")
    val name: kotlin.String,

    /* the id of the crate */
    @SerialName(value = "crateID")
    val crateID: kotlin.Long,

    /* the ordering in the tab panel */
    @SerialName(value = "ordering")
    val ordering: kotlin.Int,

    /* the icon name */
    @SerialName(value = "icon")
    val icon: kotlin.String,

    /* indicates if the tabs has been removed from the user */
    @SerialName(value = "removed")
    val removed: kotlin.Boolean,

    /* indicates whether the crate exists in the system */
    @SerialName(value = "crateExists")
    val crateExists: kotlin.Boolean

) {


}

