/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents a tab's attributes. It is used to save the order of tabs in the user preferences file
 *
 * @param orderID the ordering in the tab panel
 * @param crateID the crate ID
 */
@Serializable

public data class TabCrateListElement (

    /* the ordering in the tab panel */
    @SerialName(value = "orderID")
    val orderID: kotlin.Int,

    /* the crate ID */
    @SerialName(value = "crateID")
    val crateID: kotlin.Long

) {


}

