/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents a tune timestamped comment
 *
 * @param tuneID owning tune id
 * @param text HTML comment body text
 * @param seconds timestamp position in seconds
 * @param commentID comment id
 * @param userId user id that authored the comment
 * @param dateCreated creation timestamp
 * @param dateModified last update timestamp
 */
@Serializable

public data class TuneTimestampedCommentPresentationBean (

    /* owning tune id */
    @SerialName(value = "tuneID")
    val tuneID: kotlin.Long,

    /* HTML comment body text */
    @SerialName(value = "text")
    val text: kotlin.String,

    /* timestamp position in seconds */
    @SerialName(value = "seconds")
    val seconds: kotlin.Int,

    /* comment id */
    @SerialName(value = "commentID")
    val commentID: kotlin.Long? = null,

    /* user id that authored the comment */
    @SerialName(value = "userId")
    val userId: kotlin.String? = null,

    /* creation timestamp */
    @Contextual @SerialName(value = "dateCreated")
    val dateCreated: kotlin.time.Instant? = null,

    /* last update timestamp */
    @Contextual @SerialName(value = "dateModified")
    val dateModified: kotlin.time.Instant? = null

) {


}

