/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the output produced by a 'Tune_ADDDED_TO_LIBRARY' event
 *
 * @param eventType The event's type
 * @param destinationClientID The event's destinated client id to get the message. This will help the debuggin process
 * @param eventName The event's name
 * @param tune 
 */
@Serializable

public data class TuneImportedEventOutput (

    /* The event's type */
    @SerialName(value = "eventType")
    val eventType: kotlin.String,

    /* The event's destinated client id to get the message. This will help the debuggin process */
    @SerialName(value = "destinationClientID")
    val destinationClientID: kotlin.String,

    /* The event's name */
    @SerialName(value = "eventName")
    val eventName: kotlin.String,

    @Contextual @SerialName(value = "tune")
    val tune: kotlin.Any

) {


}

