/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.TuneBasicPresentationBean
import io.crates.api.models.UpdateAttributesDTO

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the DTO object to update multiple tunes on various attributes
 *
 * @param tunes a list of tune ids to be updated
 * @param attributes a list of pair attribute/value to update
 */
@Serializable

public data class UpdateTunesAttributesDTO (

    /* a list of tune ids to be updated */
    @SerialName(value = "tunes")
    val tunes: kotlin.collections.List<TuneBasicPresentationBean>,

    /* a list of pair attribute/value to update */
    @SerialName(value = "attributes")
    val attributes: kotlin.collections.List<UpdateAttributesDTO>

) {


}

