/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * This bean represents the settings with the policy to show import action when an external usb is connected
 *
 * @param deviceName the name of the device
 * @param lastConnectedAt the datetime that was last connected
 * @param showImportActionAfterSecs the time in secs to show the import action, if the policy is set to wait for a some time before reshow
 * @param showImportActionPolicy Unresolved: USBExternalDeviceShowImportActionPolicy
 */
@Serializable

public data class USBExternalDeviceSettingsElement (

    /* the name of the device */
    @SerialName(value = "deviceName")
    val deviceName: kotlin.String,

    /* the datetime that was last connected */
    @SerialName(value = "lastConnectedAt")
    val lastConnectedAt: kotlin.Long,

    /* the time in secs to show the import action, if the policy is set to wait for a some time before reshow */
    @SerialName(value = "showImportActionAfterSecs")
    val showImportActionAfterSecs: kotlin.Int,

    /* Unresolved: USBExternalDeviceShowImportActionPolicy */
    @Contextual @SerialName(value = "showImportActionPolicy")
    val showImportActionPolicy: kotlin.Any

) {


}

