/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.crates.api.models.ConversionCooldowns
import io.crates.api.models.ConversionMetrics

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param segment Unresolved: ConversionSegment
 * @param recommendedAction Unresolved: ConversionRecommendedAction
 * @param variant Unresolved: SupporterNudgeVariant
 * @param showUpgradeButton Whether the Upgrade button should be shown
 * @param eligible Whether any conversion UI is currently eligible
 * @param reason Human-readable reason for the recommendation
 * @param metrics 
 * @param cooldowns 
 */
@Serializable

public data class UserConversionStatus (

    /* Unresolved: ConversionSegment */
    @Contextual @SerialName(value = "segment")
    val segment: kotlin.Any? = null,

    /* Unresolved: ConversionRecommendedAction */
    @Contextual @SerialName(value = "recommendedAction")
    val recommendedAction: kotlin.Any? = null,

    /* Unresolved: SupporterNudgeVariant */
    @Contextual @SerialName(value = "variant")
    val variant: kotlin.Any? = null,

    /* Whether the Upgrade button should be shown */
    @SerialName(value = "showUpgradeButton")
    val showUpgradeButton: kotlin.Boolean? = null,

    /* Whether any conversion UI is currently eligible */
    @SerialName(value = "eligible")
    val eligible: kotlin.Boolean? = null,

    /* Human-readable reason for the recommendation */
    @SerialName(value = "reason")
    val reason: kotlin.String? = null,

    @SerialName(value = "metrics")
    val metrics: ConversionMetrics? = null,

    @SerialName(value = "cooldowns")
    val cooldowns: ConversionCooldowns? = null

) {


}

