/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.crates.api.models.AuthorizationConnectionInfo

import io.crates.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    public open class GdriveApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * GET /gdrive/connect
        * grant permission to Crates to access user&#39;s Google Drive Account
        * 
         * @param importFiles imports or not the google.drive collection (optional)
         * @param allowManageAccount  (optional)
         * @return AuthorizationConnectionInfo
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun gdriveConnectGdriveConnect(importFiles: kotlin.String?, allowManageAccount: kotlin.String?): HttpResponse<AuthorizationConnectionInfo> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            importFiles?.apply { localVariableQuery["importFiles"] = listOf("$importFiles") }
            allowManageAccount?.apply { localVariableQuery["allowManageAccount"] = listOf("$allowManageAccount") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/gdrive/connect",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /gdrive/disconnect
        * Disconnects from google drive
        * 
         * @return AuthorizationConnectionInfo
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun gdriveDisconnectGdriveDisconnect(): HttpResponse<AuthorizationConnectionInfo> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/gdrive/disconnect",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /gdrive/connect.status
        * gets user&#39;s name and whether or not is registered with google.drive api
        * 
         * @return AuthorizationConnectionInfo
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun gdriveGetUserConnectionStatusGdriveConnectStatus(): HttpResponse<AuthorizationConnectionInfo> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/gdrive/connect.status",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
