/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.crates.api.models.LabelPresentationBean

import io.crates.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    public open class LabelsApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * DELETE /labels/{id}
        * Deletes an label
        * 
         * @param id the id of the label 
         * @return void
        */
        public open suspend fun labelsDeleteLabelLabelsId(id: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/labels/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /labels
        * Get All Labels
        * Retrieves all imported Labels
         * @param sortingOrderId Sorting order for the artists (optional)
         * @return kotlin.collections.List<LabelPresentationBean>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun labelsGetAllLabels(sortingOrderId: kotlin.Int?): HttpResponse<kotlin.collections.List<LabelPresentationBean>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            sortingOrderId?.apply { localVariableQuery["sorting_order_id"] = listOf("$sortingOrderId") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/labels",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /labels/{id}
        * Get Label by id
        * Retrieve the label stored in the database by its id.
         * @param id the id of the label 
         * @return LabelPresentationBean
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun labelsGetLabelByIDLabelsId(id: kotlin.String): HttpResponse<LabelPresentationBean> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/labels/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /labels/tags/{tag_id}
        * Get All Labels by tag
        * Retrieves Labels from a tag
         * @param tagId the id of the tag 
         * @return kotlin.collections.List<LabelPresentationBean>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun labelsGetLabelsFromTagByIDLabelsTagsTagId(tagId: kotlin.String): HttpResponse<kotlin.collections.List<LabelPresentationBean>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/labels/tags/{tag_id}".replace("{" + "tag_id" + "}", "$tagId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /labels/tags
        * Get All Labels by tag
        * Retrieves Labels from a tag
         * @param tagname the name of the tag (optional)
         * @return kotlin.collections.List<LabelPresentationBean>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun labelsGetLabelsFromTagByNameLabelsTags(tagname: kotlin.String?): HttpResponse<kotlin.collections.List<LabelPresentationBean>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            tagname?.apply { localVariableQuery["tagname"] = listOf("$tagname") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/labels/tags",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /labels/lookup-and-update/{id}
        * Lookup label info and update the label entity 
        * 
         * @param id the id of the label 
         * @return LabelPresentationBean
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun labelsLookupAndUpdateLabelInfoLabelsLookupAndUpdateId(id: kotlin.String): HttpResponse<LabelPresentationBean> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/labels/lookup-and-update/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /labels/lookup/{id}
        * Lookup and update label info
        * 
         * @param id the id of the label 
         * @return void
        */
        public open suspend fun labelsLookupLabelInfoLabelsLookupId(id: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/labels/lookup/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /labels/update/{id}
        * Updates an label
        * 
         * @param id the id of the label 
         * @param body  
         * @return void
        */
        public open suspend fun labelsUpdateLabelFromLabelInfoLabelsUpdateId(id: kotlin.String, body: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/labels/update/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /labels/update-from-url/{id}
        * Updates an label
        * 
         * @param id the id of the label 
         * @param url the url to update the label from 
         * @return void
        */
        public open suspend fun labelsUpdateLabelFromURLLabelsUpdateFromUrlId(id: kotlin.String, url: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            url?.apply { localVariableQuery["url"] = listOf("$url") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/labels/update-from-url/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * PUT /labels
        * Updates a Label
        * 
         * @param body  
         * @return void
        */
        public open suspend fun labelsUpdateLabelLabels(body: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/labels",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
