/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.crates.api.models.EventLogPresentationBean

import io.crates.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    public open class LogsApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * DELETE /logs/{id}
        * Deletes a log
        * Deletes a log by its id
         * @param id The id of the log to delete 
         * @return void
        */
        public open suspend fun logsDeleteByIdLogsId(id: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/logs/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /logs
        * Get All Logs
        * Retrieves all logs stored in the database.
         * @return kotlin.collections.List<EventLogPresentationBean>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun logsGetAllLogsLogs(): HttpResponse<kotlin.collections.List<EventLogPresentationBean>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/logs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /logs/{id}
        * Gets a log based on its id
        * 
         * @param id The id of the log 
         * @return EventLogPresentationBean
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun logsGetLogByIDLogsId(id: kotlin.String): HttpResponse<EventLogPresentationBean> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/logs/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /logs/level
        * Get log level
        * Gets the log level for a specific logger
         * @param loggerName The name of the logger (optional)
         * @return void
        */
        public open suspend fun logsGetLogLevelLogsLevel(loggerName: kotlin.String?): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()
            loggerName?.apply { localVariableQuery["loggerName"] = listOf("$loggerName") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/logs/level",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /logs/action.types/{event_type_id}
        * Gets all logs based on log&#39;s type id
        * Gets all logs of a specific log type id
         * @param eventTypeId The id of the action type to get its logs 
         * @return kotlin.collections.List<EventLogPresentationBean>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun logsGetLogsByActionTypeIDLogsActionTypesEventTypeId(eventTypeId: kotlin.String): HttpResponse<kotlin.collections.List<EventLogPresentationBean>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/logs/action.types/{event_type_id}".replace("{" + "event_type_id" + "}", "$eventTypeId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * POST /logs/set-level
        * Set log level
        * Sets the log level for a specific logger
         * @param body  
         * @return void
        */
        public open suspend fun logsSetLogLevelLogsSetLevel(body: kotlin.String): HttpResponse<Unit> {

            val localVariableAuthNames = listOf<String>()

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/logs/set-level",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
