/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.apis

import io.crates.api.models.PlayerTargetDescription

import io.crates.api.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder

    public open class PlayerTargetApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(
        baseUrl,
        httpClientEngine,
        httpClientConfig,
    ) {

        /**
        * POST /player.target
        * adds a new target player
        * Returns the remaining target players
         * @param body  
         * @return kotlin.collections.List<PlayerTargetDescription>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun playerTargetAddTargetPlayerPlayerTarget(body: kotlin.String): HttpResponse<kotlin.collections.List<PlayerTargetDescription>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = body

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/player.target",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /player.target
        * Get all available target players
        * Returns a list of all available target players
         * @return kotlin.collections.List<PlayerTargetDescription>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun playerTargetGetAllTargetPlayersPlayerTarget(): HttpResponse<kotlin.collections.List<PlayerTargetDescription>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/player.target",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /player.target/types
        * Get all available target types
        * Returnns a list of all available target player types
         * @return kotlin.collections.List<kotlin.String>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun playerTargetGetAllTypesPlayerTargetTypes(): HttpResponse<kotlin.collections.List<kotlin.String>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/player.target/types",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /player.target/{id}
        * Get target player
        * Returnns a target player
         * @param id the id of the target player 
         * @return PlayerTargetDescription
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun playerTargetGetTargetPlayerPlayerTargetId(id: kotlin.String): HttpResponse<PlayerTargetDescription> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/player.target/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        /**
        * GET /player.target/{id}/remove
        * remove a target player
        * Returnns the remaining target players
         * @param id the id of the target player 
         * @return kotlin.collections.List<PlayerTargetDescription>
        */
            @Suppress("UNCHECKED_CAST")
        public open suspend fun playerTargetRemoveTargetPlayerPlayerTargetIdRemove(id: kotlin.String): HttpResponse<kotlin.collections.List<PlayerTargetDescription>> {

            val localVariableAuthNames = listOf<String>("ClientID")

            val localVariableBody = 
                    io.ktor.client.utils.EmptyContent

            val localVariableQuery = mutableMapOf<String, List<String>>()

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/player.target/{id}/remove".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
