/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.AudioSourcePresentationImpl

class AudioSourcePresentationImplTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AudioSourcePresentationImpl
        //val modelInstance = AudioSourcePresentationImpl()

        // to test the property `objectID` - the id of the corresponding object
        should("test objectID") {
            // uncomment below to test the property
            //modelInstance.objectID shouldBe ("TODO")
        }

        // to test the property `source` - the source of the audio
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `name` - the name of the audio source 
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `location` - the location
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `defaultAudioSourceType` - the default audio source type ID
        should("test defaultAudioSourceType") {
            // uncomment below to test the property
            //modelInstance.defaultAudioSourceType shouldBe ("TODO")
        }

        // to test the property `bitRate` - the bitRate
        should("test bitRate") {
            // uncomment below to test the property
            //modelInstance.bitRate shouldBe ("TODO")
        }

        // to test the property `bpm` - the bpm
        should("test bpm") {
            // uncomment below to test the property
            //modelInstance.bpm shouldBe ("TODO")
        }

        // to test the property `codec` - the codec
        should("test codec") {
            // uncomment below to test the property
            //modelInstance.codec shouldBe ("TODO")
        }

        // to test the property `length` - the length
        should("test length") {
            // uncomment below to test the property
            //modelInstance.length shouldBe ("TODO")
        }

        // to test the property `sampleRate` - the sampleRate
        should("test sampleRate") {
            // uncomment below to test the property
            //modelInstance.sampleRate shouldBe ("TODO")
        }

        // to test the property `status` - the status
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `dateAdded` - the date Added
        should("test dateAdded") {
            // uncomment below to test the property
            //modelInstance.dateAdded shouldBe ("TODO")
        }

        // to test the property `defaultAudioSource` - the date Added
        should("test defaultAudioSource") {
            // uncomment below to test the property
            //modelInstance.defaultAudioSource shouldBe ("TODO")
        }

        // to test the property `pageUrl` - the page url
        should("test pageUrl") {
            // uncomment below to test the property
            //modelInstance.pageUrl shouldBe ("TODO")
        }

        // to test the property `fileSize` - file size
        should("test fileSize") {
            // uncomment below to test the property
            //modelInstance.fileSize shouldBe ("TODO")
        }

        // to test the property `bitDepth` - bit depth
        should("test bitDepth") {
            // uncomment below to test the property
            //modelInstance.bitDepth shouldBe ("TODO")
        }

    }
}
