/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.AuthorizationConnectionInfo

class AuthorizationConnectionInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthorizationConnectionInfo
        //val modelInstance = AuthorizationConnectionInfo()

        // to test the property `service` - the service where the users authorizes at, use the AudioSourceType for now.. 
        should("test service") {
            // uncomment below to test the property
            //modelInstance.service shouldBe ("TODO")
        }

        // to test the property `username` - the user's username
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `connected` - indicating user has been disconnected
        should("test connected") {
            // uncomment below to test the property
            //modelInstance.connected shouldBe ("TODO")
        }

        // to test the property `denied` - indicating user has denied authorization
        should("test denied") {
            // uncomment below to test the property
            //modelInstance.denied shouldBe ("TODO")
        }

    }
}
