/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.CodecPreferences
import io.crates.api.models.CodecPreferenceElement

class CodecPreferencesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CodecPreferences
        //val modelInstance = CodecPreferences()

        // to test the property `codecPreferences` - The list of the supported codecs with their preferences to play
        should("test codecPreferences") {
            // uncomment below to test the property
            //modelInstance.codecPreferences shouldBe ("TODO")
        }

    }
}
