/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.ConfigurationSettings
import io.crates.api.models.AuthorizationConnectionInfo
import io.crates.api.models.BackupAndRecoverySettings
import io.crates.api.models.BandcampUserInfo
import io.crates.api.models.CodecPreferences
import io.crates.api.models.CopyToPreferences
import io.crates.api.models.CratesRootFolders
import io.crates.api.models.DeviceSyncSettings
import io.crates.api.models.DiscogsUserCredentials
import io.crates.api.models.ExportLibraryConfiguration
import io.crates.api.models.GemsFeedbackSettings
import io.crates.api.models.ImportItuneLibraryConfiguration
import io.crates.api.models.InitialSyncContext
import io.crates.api.models.MoveToPathRecentlyUsedPaths
import io.crates.api.models.PlayQueuePreviousContext
import io.crates.api.models.RenameActionProperties
import io.crates.api.models.SoundCloudProperties
import io.crates.api.models.TabCrateList
import io.crates.api.models.TabCratesSettings
import io.crates.api.models.TuneCollectionViewSimplePresentationBean
import io.crates.api.models.USBExternalDevicesSettings
import io.crates.api.models.UpdateTunePreferences
import io.crates.api.models.UserInfo
import io.crates.api.models.WatchFolderSettings
import io.crates.api.models.YoutubeInfo

class ConfigurationSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConfigurationSettings
        //val modelInstance = ConfigurationSettings()

        // to test the property `watchFolderSettings`
        should("test watchFolderSettings") {
            // uncomment below to test the property
            //modelInstance.watchFolderSettings shouldBe ("TODO")
        }

        // to test the property `codecPreferences`
        should("test codecPreferences") {
            // uncomment below to test the property
            //modelInstance.codecPreferences shouldBe ("TODO")
        }

        // to test the property `playQueuePreviousContext`
        should("test playQueuePreviousContext") {
            // uncomment below to test the property
            //modelInstance.playQueuePreviousContext shouldBe ("TODO")
        }

        // to test the property `usBExternalDevicesSettings`
        should("test usBExternalDevicesSettings") {
            // uncomment below to test the property
            //modelInstance.usBExternalDevicesSettings shouldBe ("TODO")
        }

        // to test the property `cratesRootFolders`
        should("test cratesRootFolders") {
            // uncomment below to test the property
            //modelInstance.cratesRootFolders shouldBe ("TODO")
        }

        // to test the property `moveToPathRecentlyUsedPaths`
        should("test moveToPathRecentlyUsedPaths") {
            // uncomment below to test the property
            //modelInstance.moveToPathRecentlyUsedPaths shouldBe ("TODO")
        }

        // to test the property `defaultCollectionViews` - default collection views
        should("test defaultCollectionViews") {
            // uncomment below to test the property
            //modelInstance.defaultCollectionViews shouldBe ("TODO")
        }

        // to test the property `userInfo`
        should("test userInfo") {
            // uncomment below to test the property
            //modelInstance.userInfo shouldBe ("TODO")
        }

        // to test the property `updateTunePreferences`
        should("test updateTunePreferences") {
            // uncomment below to test the property
            //modelInstance.updateTunePreferences shouldBe ("TODO")
        }

        // to test the property `initialSyncContext`
        should("test initialSyncContext") {
            // uncomment below to test the property
            //modelInstance.initialSyncContext shouldBe ("TODO")
        }

        // to test the property `exportLibraryConfiguration`
        should("test exportLibraryConfiguration") {
            // uncomment below to test the property
            //modelInstance.exportLibraryConfiguration shouldBe ("TODO")
        }

        // to test the property `importItuneLibraryConfiguration`
        should("test importItuneLibraryConfiguration") {
            // uncomment below to test the property
            //modelInstance.importItuneLibraryConfiguration shouldBe ("TODO")
        }

        // to test the property `copyToPreferences`
        should("test copyToPreferences") {
            // uncomment below to test the property
            //modelInstance.copyToPreferences shouldBe ("TODO")
        }

        // to test the property `renameActionProperties`
        should("test renameActionProperties") {
            // uncomment below to test the property
            //modelInstance.renameActionProperties shouldBe ("TODO")
        }

        // to test the property `tuneNamingPattern` - configuration regarding the 'rename' action params
        should("test tuneNamingPattern") {
            // uncomment below to test the property
            //modelInstance.tuneNamingPattern shouldBe ("TODO")
        }

        // to test the property `releaseNamingPattern` - configuration regarding the naming pattern of a release crate
        should("test releaseNamingPattern") {
            // uncomment below to test the property
            //modelInstance.releaseNamingPattern shouldBe ("TODO")
        }

        // to test the property `allowNonMusicYoutubeVideosToBeImportedByDefault` - if false, only videos under Music Category will be imported. if true, filter will expand to videos in non-music categories, that could be music
        should("test allowNonMusicYoutubeVideosToBeImportedByDefault") {
            // uncomment below to test the property
            //modelInstance.allowNonMusicYoutubeVideosToBeImportedByDefault shouldBe ("TODO")
        }

        // to test the property `tabCratesSettings`
        should("test tabCratesSettings") {
            // uncomment below to test the property
            //modelInstance.tabCratesSettings shouldBe ("TODO")
        }

        // to test the property `tabCrateList`
        should("test tabCrateList") {
            // uncomment below to test the property
            //modelInstance.tabCrateList shouldBe ("TODO")
        }

        // to test the property `allowServerDiscovery` - allow to register to local jmDNS to be discoverable by a mobile device on the same local network
        should("test allowServerDiscovery") {
            // uncomment below to test the property
            //modelInstance.allowServerDiscovery shouldBe ("TODO")
        }

        // to test the property `discoverExternalTargetPlayersEnable` - allow user to turn on/off external target players
        should("test discoverExternalTargetPlayersEnable") {
            // uncomment below to test the property
            //modelInstance.discoverExternalTargetPlayersEnable shouldBe ("TODO")
        }

        // to test the property `tuneMatcherEnable` - allow user to tuner on/off the crate's matcher
        should("test tuneMatcherEnable") {
            // uncomment below to test the property
            //modelInstance.tuneMatcherEnable shouldBe ("TODO")
        }

        // to test the property `importDiscogsCollectionOnConnect` - imports user collection from discogs on connect
        should("test importDiscogsCollectionOnConnect") {
            // uncomment below to test the property
            //modelInstance.importDiscogsCollectionOnConnect shouldBe ("TODO")
        }

        // to test the property `importDiscogsWantlistOnConnect` - imports user wantlist from discogs on connect
        should("test importDiscogsWantlistOnConnect") {
            // uncomment below to test the property
            //modelInstance.importDiscogsWantlistOnConnect shouldBe ("TODO")
        }

        // to test the property `discogsUserCredentials`
        should("test discogsUserCredentials") {
            // uncomment below to test the property
            //modelInstance.discogsUserCredentials shouldBe ("TODO")
        }

        // to test the property `youtubeInfo`
        should("test youtubeInfo") {
            // uncomment below to test the property
            //modelInstance.youtubeInfo shouldBe ("TODO")
        }

        // to test the property `mobileDownloadAutoConversionProfile` - When returning a stream to mobile clients, automatically select or convert to the required format according to this conversion Profile
        should("test mobileDownloadAutoConversionProfile") {
            // uncomment below to test the property
            //modelInstance.mobileDownloadAutoConversionProfile shouldBe ("TODO")
        }

        // to test the property `discogsUpdateDeep` - When updating from discogs, if this is true it will request everything in full, otherwise it will assume Artist, Label & Release Info were not changed since initial import
        should("test discogsUpdateDeep") {
            // uncomment below to test the property
            //modelInstance.discogsUpdateDeep shouldBe ("TODO")
        }

        // to test the property `importBandcampTagsEnabled` - When importing a tune or release from bandcamp, if this is true, it will get keywords from bandcamp and add as tags
        should("test importBandcampTagsEnabled") {
            // uncomment below to test the property
            //modelInstance.importBandcampTagsEnabled shouldBe ("TODO")
        }

        // to test the property `spotifyAccessToken` - Spotify Access Token
        should("test spotifyAccessToken") {
            // uncomment below to test the property
            //modelInstance.spotifyAccessToken shouldBe ("TODO")
        }

        // to test the property `spotifyRefreshToken` - Spotify Refresh Token
        should("test spotifyRefreshToken") {
            // uncomment below to test the property
            //modelInstance.spotifyRefreshToken shouldBe ("TODO")
        }

        // to test the property `spotifyAccessTokenExpDateTime` - Spotify Access Token Expiration Datetime
        should("test spotifyAccessTokenExpDateTime") {
            // uncomment below to test the property
            //modelInstance.spotifyAccessTokenExpDateTime shouldBe ("TODO")
        }

        // to test the property `spotifyImportCollection` - if user chose to import their spotify collection on the last connect
        should("test spotifyImportCollection") {
            // uncomment below to test the property
            //modelInstance.spotifyImportCollection shouldBe ("TODO")
        }

        // to test the property `spotifyApp` - Spotify App Identifier
        should("test spotifyApp") {
            // uncomment below to test the property
            //modelInstance.spotifyApp shouldBe ("TODO")
        }

        // to test the property `autoFindAudioSource` - if autoFind AudioSource service is on, it should be true, otherwise false
        should("test autoFindAudioSource") {
            // uncomment below to test the property
            //modelInstance.autoFindAudioSource shouldBe ("TODO")
        }

        // to test the property `autoFindAudioSourceServicePriorityList` - an ordered list of services that will be used to find audio source 
        should("test autoFindAudioSourceServicePriorityList") {
            // uncomment below to test the property
            //modelInstance.autoFindAudioSourceServicePriorityList shouldBe ("TODO")
        }

        // to test the property `dontAllowSpotifyTunesInNonSpotifyCrates` - if this setting is on, a spotify tune cannot be added in a crate with other streaming services tunes
        should("test dontAllowSpotifyTunesInNonSpotifyCrates") {
            // uncomment below to test the property
            //modelInstance.dontAllowSpotifyTunesInNonSpotifyCrates shouldBe ("TODO")
        }

        // to test the property `gDriveInfo`
        should("test gDriveInfo") {
            // uncomment below to test the property
            //modelInstance.gDriveInfo shouldBe ("TODO")
        }

        // to test the property `gDriveConvertAudioFilesBeforeUploading` - if this setting is on, audio files will be converted before uploading to Google Drive
        should("test gDriveConvertAudioFilesBeforeUploading") {
            // uncomment below to test the property
            //modelInstance.gDriveConvertAudioFilesBeforeUploading shouldBe ("TODO")
        }

        // to test the property `getInfoServicePriorityList` - an ordered list of services to fetch info from
        should("test getInfoServicePriorityList") {
            // uncomment below to test the property
            //modelInstance.getInfoServicePriorityList shouldBe ("TODO")
        }

        // to test the property `autoAddInOnlineSaves` - an ordered list of services to fetch info from
        should("test autoAddInOnlineSaves") {
            // uncomment below to test the property
            //modelInstance.autoAddInOnlineSaves shouldBe ("TODO")
        }

        // to test the property `autoAnalyzeBandcampOnImport`
        should("test autoAnalyzeBandcampOnImport") {
            // uncomment below to test the property
            //modelInstance.autoAnalyzeBandcampOnImport shouldBe ("TODO")
        }

        // to test the property `firstUseAt` - the timestamp when the app was first used on this machine
        should("test firstUseAt") {
            // uncomment below to test the property
            //modelInstance.firstUseAt shouldBe ("TODO")
        }

        // to test the property `supporterNudgeShownAt` - timestamps when the supporter nudge was shown
        should("test supporterNudgeShownAt") {
            // uncomment below to test the property
            //modelInstance.supporterNudgeShownAt shouldBe ("TODO")
        }

        // to test the property `supporterNudgeLastDismissedAt` - timestamp when the supporter nudge was last dismissed
        should("test supporterNudgeLastDismissedAt") {
            // uncomment below to test the property
            //modelInstance.supporterNudgeLastDismissedAt shouldBe ("TODO")
        }

        // to test the property `activationNudgeLastShownAt` - timestamp when the activation nudge was last shown
        should("test activationNudgeLastShownAt") {
            // uncomment below to test the property
            //modelInstance.activationNudgeLastShownAt shouldBe ("TODO")
        }

        // to test the property `djProfileEnabled` - if dj profile is enabled
        should("test djProfileEnabled") {
            // uncomment below to test the property
            //modelInstance.djProfileEnabled shouldBe ("TODO")
        }

        // to test the property `pluginSettings` - the plugin settings
        should("test pluginSettings") {
            // uncomment below to test the property
            //modelInstance.pluginSettings shouldBe ("TODO")
        }

        // to test the property `getInfoOnNewArtistsAndLabels` - if getInfoOnNewArtistsAndLabels is enabled
        should("test getInfoOnNewArtistsAndLabels") {
            // uncomment below to test the property
            //modelInstance.getInfoOnNewArtistsAndLabels shouldBe ("TODO")
        }

        // to test the property `getInfoOnNewReleases` - if getInfoOnNewReleases is enabled
        should("test getInfoOnNewReleases") {
            // uncomment below to test the property
            //modelInstance.getInfoOnNewReleases shouldBe ("TODO")
        }

        // to test the property `artistLabelImportScope` - Unresolved: ArtistLabelImportScope
        should("test artistLabelImportScope") {
            // uncomment below to test the property
            //modelInstance.artistLabelImportScope shouldBe ("TODO")
        }

        // to test the property `fieldToImportTagsFrom` - the ID3 field to append tags
        should("test fieldToImportTagsFrom") {
            // uncomment below to test the property
            //modelInstance.fieldToImportTagsFrom shouldBe ("TODO")
        }

        // to test the property `fieldToAppendTags` - the field to append tags
        should("test fieldToAppendTags") {
            // uncomment below to test the property
            //modelInstance.fieldToAppendTags shouldBe ("TODO")
        }

        // to test the property `gemsFeedbackSettings`
        should("test gemsFeedbackSettings") {
            // uncomment below to test the property
            //modelInstance.gemsFeedbackSettings shouldBe ("TODO")
        }

        // to test the property `cloudSyncEnabled` - if cloud sync is enabled
        should("test cloudSyncEnabled") {
            // uncomment below to test the property
            //modelInstance.cloudSyncEnabled shouldBe ("TODO")
        }

        // to test the property `cloudStorage` - Preferred cloud storage provider
        should("test cloudStorage") {
            // uncomment below to test the property
            //modelInstance.cloudStorage shouldBe ("TODO")
        }

        // to test the property `mobileDeviceSyncSettings` - List of sync settings for each connected mobile device
        should("test mobileDeviceSyncSettings") {
            // uncomment below to test the property
            //modelInstance.mobileDeviceSyncSettings shouldBe ("TODO")
        }

        // to test the property `checkForBetterAudioSourceOnPlayback` - Checks if a higher-quality audio source is available on playback
        should("test checkForBetterAudioSourceOnPlayback") {
            // uncomment below to test the property
            //modelInstance.checkForBetterAudioSourceOnPlayback shouldBe ("TODO")
        }

        // to test the property `spotifyProfileEnabled` - spotifyProfileEnabled
        should("test spotifyProfileEnabled") {
            // uncomment below to test the property
            //modelInstance.spotifyProfileEnabled shouldBe ("TODO")
        }

        // to test the property `spotifyEmail` - Spotify Email
        should("test spotifyEmail") {
            // uncomment below to test the property
            //modelInstance.spotifyEmail shouldBe ("TODO")
        }

        // to test the property `soundCloudProperties`
        should("test soundCloudProperties") {
            // uncomment below to test the property
            //modelInstance.soundCloudProperties shouldBe ("TODO")
        }

        // to test the property `bandcampUserInfo`
        should("test bandcampUserInfo") {
            // uncomment below to test the property
            //modelInstance.bandcampUserInfo shouldBe ("TODO")
        }

        // to test the property `bandcampCollectionImportCursors` - The last successful Bandcamp collection import cursor per account
        should("test bandcampCollectionImportCursors") {
            // uncomment below to test the property
            //modelInstance.bandcampCollectionImportCursors shouldBe ("TODO")
        }

        // to test the property `youtubeCollectionImportCursors` - The last successful YouTube collection import cursor per account
        should("test youtubeCollectionImportCursors") {
            // uncomment below to test the property
            //modelInstance.youtubeCollectionImportCursors shouldBe ("TODO")
        }

        // to test the property `youtubePlaylistImportCursors` - The last successful YouTube playlist import cursor per playlist
        should("test youtubePlaylistImportCursors") {
            // uncomment below to test the property
            //modelInstance.youtubePlaylistImportCursors shouldBe ("TODO")
        }

        // to test the property `preferUIPlayer` - preferUIPlayer
        should("test preferUIPlayer") {
            // uncomment below to test the property
            //modelInstance.preferUIPlayer shouldBe ("TODO")
        }

        // to test the property `backupAndRecoverySettings`
        should("test backupAndRecoverySettings") {
            // uncomment below to test the property
            //modelInstance.backupAndRecoverySettings shouldBe ("TODO")
        }

    }
}
