/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.ConversionMetrics

class ConversionMetricsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConversionMetrics
        //val modelInstance = ConversionMetrics()

        // to test the property `daysSinceFirstUse` - Days since the first run of the app
        should("test daysSinceFirstUse") {
            // uncomment below to test the property
            //modelInstance.daysSinceFirstUse shouldBe ("TODO")
        }

        // to test the property `tuneCount` - Total number of tunes in the library
        should("test tuneCount") {
            // uncomment below to test the property
            //modelInstance.tuneCount shouldBe ("TODO")
        }

        // to test the property `importedSourceCount` - Number of distinct imported source families
        should("test importedSourceCount") {
            // uncomment below to test the property
            //modelInstance.importedSourceCount shouldBe ("TODO")
        }

        // to test the property `importedSources` - Distinct imported source families
        should("test importedSources") {
            // uncomment below to test the property
            //modelInstance.importedSources shouldBe ("TODO")
        }

    }
}
