/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.CratesRootFolders

class CratesRootFoldersTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CratesRootFolders
        //val modelInstance = CratesRootFolders()

        // to test the property `cratesRootFolder` - The root folder of all
        should("test cratesRootFolder") {
            // uncomment below to test the property
            //modelInstance.cratesRootFolder shouldBe ("TODO")
        }

        // to test the property `djLibraryRootFolder` - The dj library root folder
        should("test djLibraryRootFolder") {
            // uncomment below to test the property
            //modelInstance.djLibraryRootFolder shouldBe ("TODO")
        }

        // to test the property `archiveRootFolder` - The archive root folder
        should("test archiveRootFolder") {
            // uncomment below to test the property
            //modelInstance.archiveRootFolder shouldBe ("TODO")
        }

        // to test the property `incomingRootFolder` - The incoming root folder
        should("test incomingRootFolder") {
            // uncomment below to test the property
            //modelInstance.incomingRootFolder shouldBe ("TODO")
        }

        // to test the property `collectionsRootFolder` - The incoming root folder
        should("test collectionsRootFolder") {
            // uncomment below to test the property
            //modelInstance.collectionsRootFolder shouldBe ("TODO")
        }

        // to test the property `collectionTunesFolder`
        should("test collectionTunesFolder") {
            // uncomment below to test the property
            //modelInstance.collectionTunesFolder shouldBe ("TODO")
        }

        // to test the property `collectionReleasesFolder`
        should("test collectionReleasesFolder") {
            // uncomment below to test the property
            //modelInstance.collectionReleasesFolder shouldBe ("TODO")
        }

    }
}
