/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.CrateTabsPresentationBean

class CrateTabsPresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CrateTabsPresentationBean
        //val modelInstance = CrateTabsPresentationBean()

        // to test the property `orderID` - the crate's order in the list of tabs
        should("test orderID") {
            // uncomment below to test the property
            //modelInstance.orderID shouldBe ("TODO")
        }

        // to test the property `subCrateSortingOrderID`
        should("test subCrateSortingOrderID") {
            // uncomment below to test the property
            //modelInstance.subCrateSortingOrderID shouldBe ("TODO")
        }

        // to test the property `crateID`
        should("test crateID") {
            // uncomment below to test the property
            //modelInstance.crateID shouldBe ("TODO")
        }

        // to test the property `crateName`
        should("test crateName") {
            // uncomment below to test the property
            //modelInstance.crateName shouldBe ("TODO")
        }

        // to test the property `iconClass`
        should("test iconClass") {
            // uncomment below to test the property
            //modelInstance.iconClass shouldBe ("TODO")
        }

        // to test the property `crateTypeID`
        should("test crateTypeID") {
            // uncomment below to test the property
            //modelInstance.crateTypeID shouldBe ("TODO")
        }

    }
}
