/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.CrateTypePresentationBean

class CrateTypePresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CrateTypePresentationBean
        //val modelInstance = CrateTypePresentationBean()

        // to test the property `typeID` - the crate type's ID
        should("test typeID") {
            // uncomment below to test the property
            //modelInstance.typeID shouldBe ("TODO")
        }

        // to test the property `typeName` - the crate type's name
        should("test typeName") {
            // uncomment below to test the property
            //modelInstance.typeName shouldBe ("TODO")
        }

        // to test the property `defaultIconClass` - the crate type's name
        should("test defaultIconClass") {
            // uncomment below to test the property
            //modelInstance.defaultIconClass shouldBe ("TODO")
        }

    }
}
