/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.CustomAttributeTypePresentationBean

class CustomAttributeTypePresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CustomAttributeTypePresentationBean
        //val modelInstance = CustomAttributeTypePresentationBean()

        // to test the property `customAttributeID` - the custom attribute's ID
        should("test customAttributeID") {
            // uncomment below to test the property
            //modelInstance.customAttributeID shouldBe ("TODO")
        }

        // to test the property `customAttributeName` - the custom attribute's name
        should("test customAttributeName") {
            // uncomment below to test the property
            //modelInstance.customAttributeName shouldBe ("TODO")
        }

    }
}
