/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.DeviceSyncSettings

class DeviceSyncSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeviceSyncSettings
        //val modelInstance = DeviceSyncSettings()

        // to test the property `deviceName` - The device name or ID
        should("test deviceName") {
            // uncomment below to test the property
            //modelInstance.deviceName shouldBe ("TODO")
        }

        // to test the property `deviceUid` - Unique identifier for the device
        should("test deviceUid") {
            // uncomment below to test the property
            //modelInstance.deviceUid shouldBe ("TODO")
        }

        // to test the property `platform` - Platform (iOS, Android, etc)
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `model` - Device model (e.g. iPhone 13)
        should("test model") {
            // uncomment below to test the property
            //modelInstance.model shouldBe ("TODO")
        }

        // to test the property `arch` - CPU architecture (e.g. arm64)
        should("test arch") {
            // uncomment below to test the property
            //modelInstance.arch shouldBe ("TODO")
        }

        // to test the property `storageLimitMB` - Storage allowed for syncing on this device in MB
        should("test storageLimitMB") {
            // uncomment below to test the property
            //modelInstance.storageLimitMB shouldBe ("TODO")
        }

        // to test the property `maxStorageLimitMB` - Max storage allowed for syncing on this device in MB
        should("test maxStorageLimitMB") {
            // uncomment below to test the property
            //modelInstance.maxStorageLimitMB shouldBe ("TODO")
        }

        // to test the property `conversionFormat` - Conversion format used for downloads on this device
        should("test conversionFormat") {
            // uncomment below to test the property
            //modelInstance.conversionFormat shouldBe ("TODO")
        }

        // to test the property `autoDownloadEnabled` - Whether automatic downloads are enabled
        should("test autoDownloadEnabled") {
            // uncomment below to test the property
            //modelInstance.autoDownloadEnabled shouldBe ("TODO")
        }

        // to test the property `favoritesRecentsPriorityPercent` - Percentage priority given to favorites over recents
        should("test favoritesRecentsPriorityPercent") {
            // uncomment below to test the property
            //modelInstance.favoritesRecentsPriorityPercent shouldBe ("TODO")
        }

    }
}
