/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.EventTypePresentationBean

class EventTypePresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EventTypePresentationBean
        //val modelInstance = EventTypePresentationBean()

        // to test the property `eventTypeID` - the eventTypeID
        should("test eventTypeID") {
            // uncomment below to test the property
            //modelInstance.eventTypeID shouldBe ("TODO")
        }

        // to test the property `eventTypeDescription` - the event's description
        should("test eventTypeDescription") {
            // uncomment below to test the property
            //modelInstance.eventTypeDescription shouldBe ("TODO")
        }

        // to test the property `eventPattern` - the event's diplay pattern
        should("test eventPattern") {
            // uncomment below to test the property
            //modelInstance.eventPattern shouldBe ("TODO")
        }

    }
}
