/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.ExportLibraryConfiguration
import io.crates.api.models.ExportLibrarySchedulerConfiguration

class ExportLibraryConfigurationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExportLibraryConfiguration
        //val modelInstance = ExportLibraryConfiguration()

        // to test the property `exportPath` - path to export the xml
        should("test exportPath") {
            // uncomment below to test the property
            //modelInstance.exportPath shouldBe ("TODO")
        }

        // to test the property `schedulerConfiguration`
        should("test schedulerConfiguration") {
            // uncomment below to test the property
            //modelInstance.schedulerConfiguration shouldBe ("TODO")
        }

    }
}
