/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.GemsFeedbackStatsPresentation
import io.crates.api.models.GemStat
import io.crates.api.models.Highlight

class GemsFeedbackStatsPresentationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GemsFeedbackStatsPresentation
        //val modelInstance = GemsFeedbackStatsPresentation()

        // to test the property `gemsPosted`
        should("test gemsPosted") {
            // uncomment below to test the property
            //modelInstance.gemsPosted shouldBe ("TODO")
        }

        // to test the property `revealsReceived`
        should("test revealsReceived") {
            // uncomment below to test the property
            //modelInstance.revealsReceived shouldBe ("TODO")
        }

        // to test the property `gemsDiscovered`
        should("test gemsDiscovered") {
            // uncomment below to test the property
            //modelInstance.gemsDiscovered shouldBe ("TODO")
        }

        // to test the property `downvotesReceived`
        should("test downvotesReceived") {
            // uncomment below to test the property
            //modelInstance.downvotesReceived shouldBe ("TODO")
        }

        // to test the property `passesReceived`
        should("test passesReceived") {
            // uncomment below to test the property
            //modelInstance.passesReceived shouldBe ("TODO")
        }

        // to test the property `revealCounts`
        should("test revealCounts") {
            // uncomment below to test the property
            //modelInstance.revealCounts shouldBe ("TODO")
        }

        // to test the property `highlightCandidates`
        should("test highlightCandidates") {
            // uncomment below to test the property
            //modelInstance.highlightCandidates shouldBe ("TODO")
        }

        // to test the property `topRevealStats`
        should("test topRevealStats") {
            // uncomment below to test the property
            //modelInstance.topRevealStats shouldBe ("TODO")
        }

        // to test the property `gemsDiscoveredTopRevealStats`
        should("test gemsDiscoveredTopRevealStats") {
            // uncomment below to test the property
            //modelInstance.gemsDiscoveredTopRevealStats shouldBe ("TODO")
        }

        // to test the property `gemsDiscoveredRevealCounts`
        should("test gemsDiscoveredRevealCounts") {
            // uncomment below to test the property
            //modelInstance.gemsDiscoveredRevealCounts shouldBe ("TODO")
        }

        // to test the property `ownerRevealCounts`
        should("test ownerRevealCounts") {
            // uncomment below to test the property
            //modelInstance.ownerRevealCounts shouldBe ("TODO")
        }

        // to test the property `ownerDownvoteCounts`
        should("test ownerDownvoteCounts") {
            // uncomment below to test the property
            //modelInstance.ownerDownvoteCounts shouldBe ("TODO")
        }

        // to test the property `ownerPassCounts`
        should("test ownerPassCounts") {
            // uncomment below to test the property
            //modelInstance.ownerPassCounts shouldBe ("TODO")
        }

        // to test the property `startBlock`
        should("test startBlock") {
            // uncomment below to test the property
            //modelInstance.startBlock shouldBe ("TODO")
        }

        // to test the property `endBlock`
        should("test endBlock") {
            // uncomment below to test the property
            //modelInstance.endBlock shouldBe ("TODO")
        }

        // to test the property `startTimestampMillis`
        should("test startTimestampMillis") {
            // uncomment below to test the property
            //modelInstance.startTimestampMillis shouldBe ("TODO")
        }

        // to test the property `endTimestampMillis`
        should("test endTimestampMillis") {
            // uncomment below to test the property
            //modelInstance.endTimestampMillis shouldBe ("TODO")
        }

    }
}
