/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.ImagePresentationBean

class ImagePresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ImagePresentationBean
        //val modelInstance = ImagePresentationBean()

        // to test the property `imageID` - the tag's ID
        should("test imageID") {
            // uncomment below to test the property
            //modelInstance.imageID shouldBe ("TODO")
        }

        // to test the property `source` - the tag's source
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `sourceTypeId`
        should("test sourceTypeId") {
            // uncomment below to test the property
            //modelInstance.sourceTypeId shouldBe ("TODO")
        }

        // to test the property `sizeTypeId`
        should("test sizeTypeId") {
            // uncomment below to test the property
            //modelInstance.sizeTypeId shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `propertySize`
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

    }
}
