/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.InterestBO

class InterestBOTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InterestBO
        //val modelInstance = InterestBO()

        // to test the property `entityStatus` - Unresolved: BaseObjectStatus
        should("test entityStatus") {
            // uncomment below to test the property
            //modelInstance.entityStatus shouldBe ("TODO")
        }

        // to test the property `interestID`
        should("test interestID") {
            // uncomment below to test the property
            //modelInstance.interestID shouldBe ("TODO")
        }

        // to test the property `dateAdded`
        should("test dateAdded") {
            // uncomment below to test the property
            //modelInstance.dateAdded shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `interestValue`
        should("test interestValue") {
            // uncomment below to test the property
            //modelInstance.interestValue shouldBe ("TODO")
        }

        // to test the property `discogsID`
        should("test discogsID") {
            // uncomment below to test the property
            //modelInstance.discogsID shouldBe ("TODO")
        }

        // to test the property `explicitImport`
        should("test explicitImport") {
            // uncomment below to test the property
            //modelInstance.explicitImport shouldBe ("TODO")
        }

        // to test the property `allowReImport`
        should("test allowReImport") {
            // uncomment below to test the property
            //modelInstance.allowReImport shouldBe ("TODO")
        }

    }
}
