/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.InterestGenrePresentationBean
import io.crates.api.models.InterestAbstractImpl

class InterestGenrePresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InterestGenrePresentationBean
        //val modelInstance = InterestGenrePresentationBean()

        // to test the property `interestID` - the interests's ID
        should("test interestID") {
            // uncomment below to test the property
            //modelInstance.interestID shouldBe ("TODO")
        }

        // to test the property `dateAdded` - the interests's dateAdded
        should("test dateAdded") {
            // uncomment below to test the property
            //modelInstance.dateAdded shouldBe ("TODO")
        }

        // to test the property `type` - the interests's type
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``value`` - the interests's value
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `discogsID` - the interests's discogsID
        should("test discogsID") {
            // uncomment below to test the property
            //modelInstance.discogsID shouldBe ("TODO")
        }

        // to test the property `explicitImport` - the interests's indication whether or not is from explicit reimport
        should("test explicitImport") {
            // uncomment below to test the property
            //modelInstance.explicitImport shouldBe ("TODO")
        }

        // to test the property `allowReImport` - the interests's indication whether or not explicitly allows reimport
        should("test allowReImport") {
            // uncomment below to test the property
            //modelInstance.allowReImport shouldBe ("TODO")
        }

        // to test the property `interestAbstractImpl`
        should("test interestAbstractImpl") {
            // uncomment below to test the property
            //modelInstance.interestAbstractImpl shouldBe ("TODO")
        }

    }
}
