/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.InterestPresentationBean
import io.crates.api.models.InterestArtistPresentationBean
import io.crates.api.models.InterestGenrePresentationBean
import io.crates.api.models.InterestLabelPresentationBean

class InterestPresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InterestPresentationBean
        //val modelInstance = InterestPresentationBean()

        // to test the property `artistsInterests` - the list of interests for artists
        should("test artistsInterests") {
            // uncomment below to test the property
            //modelInstance.artistsInterests shouldBe ("TODO")
        }

        // to test the property `labelsInterests` - the list of interests for labels
        should("test labelsInterests") {
            // uncomment below to test the property
            //modelInstance.labelsInterests shouldBe ("TODO")
        }

        // to test the property `genreInterests`
        should("test genreInterests") {
            // uncomment below to test the property
            //modelInstance.genreInterests shouldBe ("TODO")
        }

    }
}
