/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.LabelSimplePresentationBean

class LabelSimplePresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LabelSimplePresentationBean
        //val modelInstance = LabelSimplePresentationBean()

        // to test the property `labelID`
        should("test labelID") {
            // uncomment below to test the property
            //modelInstance.labelID shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `thumbImageID`
        should("test thumbImageID") {
            // uncomment below to test the property
            //modelInstance.thumbImageID shouldBe ("TODO")
        }

        // to test the property `imageIDs`
        should("test imageIDs") {
            // uncomment below to test the property
            //modelInstance.imageIDs shouldBe ("TODO")
        }

    }
}
