/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.PlayerTargetDescription

class PlayerTargetDescriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PlayerTargetDescription
        //val modelInstance = PlayerTargetDescription()

        // to test the property `playerTargetID` - its id (as assigned by crates)
        should("test playerTargetID") {
            // uncomment below to test the property
            //modelInstance.playerTargetID shouldBe ("TODO")
        }

        // to test the property `playerType` - its player type
        should("test playerType") {
            // uncomment below to test the property
            //modelInstance.playerType shouldBe ("TODO")
        }

        // to test the property `jmdnsPlayerID` - its id as assigned by local network
        should("test jmdnsPlayerID") {
            // uncomment below to test the property
            //modelInstance.jmdnsPlayerID shouldBe ("TODO")
        }

        // to test the property `playerName` - its name
        should("test playerName") {
            // uncomment below to test the property
            //modelInstance.playerName shouldBe ("TODO")
        }

        // to test the property `playerModel` - its model name
        should("test playerModel") {
            // uncomment below to test the property
            //modelInstance.playerModel shouldBe ("TODO")
        }

        // to test the property `playerIPAddress` - its ip address
        should("test playerIPAddress") {
            // uncomment below to test the property
            //modelInstance.playerIPAddress shouldBe ("TODO")
        }

        // to test the property `online`
        should("test online") {
            // uncomment below to test the property
            //modelInstance.online shouldBe ("TODO")
        }

    }
}
