/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.PostedGemInfo
import io.crates.api.models.LookupUserDetails

class PostedGemInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostedGemInfo
        //val modelInstance = PostedGemInfo()

        // to test the property `tuneTitle` - tuneTitle
        should("test tuneTitle") {
            // uncomment below to test the property
            //modelInstance.tuneTitle shouldBe ("TODO")
        }

        // to test the property `tuneArtist` - tuneArtist
        should("test tuneArtist") {
            // uncomment below to test the property
            //modelInstance.tuneArtist shouldBe ("TODO")
        }

        // to test the property `tags` - tags
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `userComment` - userComment
        should("test userComment") {
            // uncomment below to test the property
            //modelInstance.userComment shouldBe ("TODO")
        }

        // to test the property `sourceURL` - sourceURL
        should("test sourceURL") {
            // uncomment below to test the property
            //modelInstance.sourceURL shouldBe ("TODO")
        }

        // to test the property `streamURL` - streamURL
        should("test streamURL") {
            // uncomment below to test the property
            //modelInstance.streamURL shouldBe ("TODO")
        }

        // to test the property `imageURL` - imageURL
        should("test imageURL") {
            // uncomment below to test the property
            //modelInstance.imageURL shouldBe ("TODO")
        }

        // to test the property `gemId` - gemID
        should("test gemId") {
            // uncomment below to test the property
            //modelInstance.gemId shouldBe ("TODO")
        }

        // to test the property `price` - price
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `posterAddress` - posterAddress
        should("test posterAddress") {
            // uncomment below to test the property
            //modelInstance.posterAddress shouldBe ("TODO")
        }

        // to test the property `audioSourceTypeId` - audioSourceTypeId
        should("test audioSourceTypeId") {
            // uncomment below to test the property
            //modelInstance.audioSourceTypeId shouldBe ("TODO")
        }

        // to test the property `datePosted` - datePosted
        should("test datePosted") {
            // uncomment below to test the property
            //modelInstance.datePosted shouldBe ("TODO")
        }

        // to test the property `repScore` - repScore
        should("test repScore") {
            // uncomment below to test the property
            //modelInstance.repScore shouldBe ("TODO")
        }

        // to test the property `userDetails`
        should("test userDetails") {
            // uncomment below to test the property
            //modelInstance.userDetails shouldBe ("TODO")
        }

    }
}
