/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.QueryVariable

class QueryVariableTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryVariable
        //val modelInstance = QueryVariable()

        // to test the property `displayName` - the name to display to the user
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `columnName` - the columnName
        should("test columnName") {
            // uncomment below to test the property
            //modelInstance.columnName shouldBe ("TODO")
        }

        // to test the property `tableName` - the tablename
        should("test tableName") {
            // uncomment below to test the property
            //modelInstance.tableName shouldBe ("TODO")
        }

        // to test the property `type` - Unresolved: CratesColumnType
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
