/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.ReleasePresentationBean

class ReleasePresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReleasePresentationBean
        //val modelInstance = ReleasePresentationBean()

        // to test the property `releaseID` - the release's ID
        should("test releaseID") {
            // uncomment below to test the property
            //modelInstance.releaseID shouldBe ("TODO")
        }

        // to test the property `name` - the release's name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `releaseYear` - the release's releaseYear
        should("test releaseYear") {
            // uncomment below to test the property
            //modelInstance.releaseYear shouldBe ("TODO")
        }

        // to test the property `catalogNo` - the release's catalogNo
        should("test catalogNo") {
            // uncomment below to test the property
            //modelInstance.catalogNo shouldBe ("TODO")
        }

        // to test the property `upc` - the release's upc
        should("test upc") {
            // uncomment below to test the property
            //modelInstance.upc shouldBe ("TODO")
        }

        // to test the property `discogsUrl` - the release's discogsUrl
        should("test discogsUrl") {
            // uncomment below to test the property
            //modelInstance.discogsUrl shouldBe ("TODO")
        }

        // to test the property `discogsID` - the release's discogsID
        should("test discogsID") {
            // uncomment below to test the property
            //modelInstance.discogsID shouldBe ("TODO")
        }

        // to test the property `country` - the release's country
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `released` - the release's released attribute
        should("test released") {
            // uncomment below to test the property
            //modelInstance.released shouldBe ("TODO")
        }

        // to test the property `releaseType` - the release's releaseType
        should("test releaseType") {
            // uncomment below to test the property
            //modelInstance.releaseType shouldBe ("TODO")
        }

        // to test the property `artistName` - the release's artistName
        should("test artistName") {
            // uncomment below to test the property
            //modelInstance.artistName shouldBe ("TODO")
        }

        // to test the property `labelName` - the release's labelName
        should("test labelName") {
            // uncomment below to test the property
            //modelInstance.labelName shouldBe ("TODO")
        }

        // to test the property `coverID` - the release's labelName
        should("test coverID") {
            // uncomment below to test the property
            //modelInstance.coverID shouldBe ("TODO")
        }

        // to test the property `artistID`
        should("test artistID") {
            // uncomment below to test the property
            //modelInstance.artistID shouldBe ("TODO")
        }

        // to test the property `labelID`
        should("test labelID") {
            // uncomment below to test the property
            //modelInstance.labelID shouldBe ("TODO")
        }

        // to test the property `crateID`
        should("test crateID") {
            // uncomment below to test the property
            //modelInstance.crateID shouldBe ("TODO")
        }

        // to test the property `url`
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `dateDiscovered` - the date when the release was discovered
        should("test dateDiscovered") {
            // uncomment below to test the property
            //modelInstance.dateDiscovered shouldBe ("TODO")
        }

    }
}
