/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.RenameActionPropertiesPresentationBean

class RenameActionPropertiesPresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RenameActionPropertiesPresentationBean
        //val modelInstance = RenameActionPropertiesPresentationBean()

        // to test the property `renameProperty` - the renameProperty
        should("test renameProperty") {
            // uncomment below to test the property
            //modelInstance.renameProperty shouldBe ("TODO")
        }

        // to test the property `renamePropertyDisplay` - the display name of the renameProperty
        should("test renamePropertyDisplay") {
            // uncomment below to test the property
            //modelInstance.renamePropertyDisplay shouldBe ("TODO")
        }

    }
}
