/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.SoundCloudUserStatusPresentationBean

class SoundCloudUserStatusPresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SoundCloudUserStatusPresentationBean
        //val modelInstance = SoundCloudUserStatusPresentationBean()

        // to test the property `username` - the user's username
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

        // to test the property `password` - the user's password
        should("test password") {
            // uncomment below to test the property
            //modelInstance.password shouldBe ("TODO")
        }

        // to test the property `connected` - status regarding if user is connected or not
        should("test connected") {
            // uncomment below to test the property
            //modelInstance.connected shouldBe ("TODO")
        }

        // to test the property `importTunes` - indicating whether to import tunes from soundcloud or not
        should("test importTunes") {
            // uncomment below to test the property
            //modelInstance.importTunes shouldBe ("TODO")
        }

        // to test the property `importPlaylists` - indicating whether to import playlists from soundcloud or not
        should("test importPlaylists") {
            // uncomment below to test the property
            //modelInstance.importPlaylists shouldBe ("TODO")
        }

    }
}
