/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.SoundCloudAppTokenPresentationBean

class SoundCloudAppTokenPresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SoundCloudAppTokenPresentationBean
        //val modelInstance = SoundCloudAppTokenPresentationBean()

        // to test the property `appID` - the application's id
        should("test appID") {
            // uncomment below to test the property
            //modelInstance.appID shouldBe ("TODO")
        }

        // to test the property `appSecret` - the application's secret
        should("test appSecret") {
            // uncomment below to test the property
            //modelInstance.appSecret shouldBe ("TODO")
        }

    }
}
