/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.TabCrateListElement

class TabCrateListElementTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TabCrateListElement
        //val modelInstance = TabCrateListElement()

        // to test the property `orderID` - the ordering in the tab panel
        should("test orderID") {
            // uncomment below to test the property
            //modelInstance.orderID shouldBe ("TODO")
        }

        // to test the property `crateID` - the crate ID
        should("test crateID") {
            // uncomment below to test the property
            //modelInstance.crateID shouldBe ("TODO")
        }

    }
}
