/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.TagPresentationBean

class TagPresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TagPresentationBean
        //val modelInstance = TagPresentationBean()

        // to test the property `tagID` - the tag's ID
        should("test tagID") {
            // uncomment below to test the property
            //modelInstance.tagID shouldBe ("TODO")
        }

        // to test the property `name` - the tag's name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
