/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.Tempo

class TempoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Tempo
        //val modelInstance = Tempo()

        // to test the property `inizio`
        should("test inizio") {
            // uncomment below to test the property
            //modelInstance.inizio shouldBe ("TODO")
        }

        // to test the property `bpm`
        should("test bpm") {
            // uncomment below to test the property
            //modelInstance.bpm shouldBe ("TODO")
        }

        // to test the property `metro`
        should("test metro") {
            // uncomment below to test the property
            //modelInstance.metro shouldBe ("TODO")
        }

        // to test the property `battito`
        should("test battito") {
            // uncomment below to test the property
            //modelInstance.battito shouldBe ("TODO")
        }

    }
}
