/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.Track
import io.crates.api.models.PositionMark
import io.crates.api.models.Tempo

class TrackTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Track
        //val modelInstance = Track()

        // to test the property `trackID`
        should("test trackID") {
            // uncomment below to test the property
            //modelInstance.trackID shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `artist`
        should("test artist") {
            // uncomment below to test the property
            //modelInstance.artist shouldBe ("TODO")
        }

        // to test the property `composer`
        should("test composer") {
            // uncomment below to test the property
            //modelInstance.composer shouldBe ("TODO")
        }

        // to test the property `album`
        should("test album") {
            // uncomment below to test the property
            //modelInstance.album shouldBe ("TODO")
        }

        // to test the property `grouping`
        should("test grouping") {
            // uncomment below to test the property
            //modelInstance.grouping shouldBe ("TODO")
        }

        // to test the property `genre`
        should("test genre") {
            // uncomment below to test the property
            //modelInstance.genre shouldBe ("TODO")
        }

        // to test the property `kind`
        should("test kind") {
            // uncomment below to test the property
            //modelInstance.kind shouldBe ("TODO")
        }

        // to test the property `propertySize`
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `totalTime`
        should("test totalTime") {
            // uncomment below to test the property
            //modelInstance.totalTime shouldBe ("TODO")
        }

        // to test the property `discNumber`
        should("test discNumber") {
            // uncomment below to test the property
            //modelInstance.discNumber shouldBe ("TODO")
        }

        // to test the property `trackNumber`
        should("test trackNumber") {
            // uncomment below to test the property
            //modelInstance.trackNumber shouldBe ("TODO")
        }

        // to test the property `year`
        should("test year") {
            // uncomment below to test the property
            //modelInstance.year shouldBe ("TODO")
        }

        // to test the property `averageBpm`
        should("test averageBpm") {
            // uncomment below to test the property
            //modelInstance.averageBpm shouldBe ("TODO")
        }

        // to test the property `dateModified`
        should("test dateModified") {
            // uncomment below to test the property
            //modelInstance.dateModified shouldBe ("TODO")
        }

        // to test the property `dateAdded`
        should("test dateAdded") {
            // uncomment below to test the property
            //modelInstance.dateAdded shouldBe ("TODO")
        }

        // to test the property `bitRate`
        should("test bitRate") {
            // uncomment below to test the property
            //modelInstance.bitRate shouldBe ("TODO")
        }

        // to test the property `sampleRate`
        should("test sampleRate") {
            // uncomment below to test the property
            //modelInstance.sampleRate shouldBe ("TODO")
        }

        // to test the property `comments`
        should("test comments") {
            // uncomment below to test the property
            //modelInstance.comments shouldBe ("TODO")
        }

        // to test the property `playCount`
        should("test playCount") {
            // uncomment below to test the property
            //modelInstance.playCount shouldBe ("TODO")
        }

        // to test the property `lastPlayed`
        should("test lastPlayed") {
            // uncomment below to test the property
            //modelInstance.lastPlayed shouldBe ("TODO")
        }

        // to test the property `rating`
        should("test rating") {
            // uncomment below to test the property
            //modelInstance.rating shouldBe ("TODO")
        }

        // to test the property `location`
        should("test location") {
            // uncomment below to test the property
            //modelInstance.location shouldBe ("TODO")
        }

        // to test the property `remixer`
        should("test remixer") {
            // uncomment below to test the property
            //modelInstance.remixer shouldBe ("TODO")
        }

        // to test the property `tonality`
        should("test tonality") {
            // uncomment below to test the property
            //modelInstance.tonality shouldBe ("TODO")
        }

        // to test the property `label`
        should("test label") {
            // uncomment below to test the property
            //modelInstance.label shouldBe ("TODO")
        }

        // to test the property `mix`
        should("test mix") {
            // uncomment below to test the property
            //modelInstance.mix shouldBe ("TODO")
        }

        // to test the property `colour`
        should("test colour") {
            // uncomment below to test the property
            //modelInstance.colour shouldBe ("TODO")
        }

        // to test the property `tempoList`
        should("test tempoList") {
            // uncomment below to test the property
            //modelInstance.tempoList shouldBe ("TODO")
        }

        // to test the property `positionMarks`
        should("test positionMarks") {
            // uncomment below to test the property
            //modelInstance.positionMarks shouldBe ("TODO")
        }

    }
}
