/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.TuneCollectionViewFieldPresentationBean

class TuneCollectionViewFieldPresentationBeanTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TuneCollectionViewFieldPresentationBean
        //val modelInstance = TuneCollectionViewFieldPresentationBean()

        // to test the property `tuneModelFieldID` - the tuneModelFieldID
        should("test tuneModelFieldID") {
            // uncomment below to test the property
            //modelInstance.tuneModelFieldID shouldBe ("TODO")
        }

        // to test the property `fieldName` - fieldName. this must match exactly with an attribute of the TunePresentationBean
        should("test fieldName") {
            // uncomment below to test the property
            //modelInstance.fieldName shouldBe ("TODO")
        }

        // to test the property `displayName` - displayName
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `columnWidth` - columnWidth
        should("test columnWidth") {
            // uncomment below to test the property
            //modelInstance.columnWidth shouldBe ("TODO")
        }

        // to test the property `visible` - visible
        should("test visible") {
            // uncomment below to test the property
            //modelInstance.visible shouldBe ("TODO")
        }

        // to test the property `editable` - editable
        should("test editable") {
            // uncomment below to test the property
            //modelInstance.editable shouldBe ("TODO")
        }

        // to test the property `resizable` - resizable
        should("test resizable") {
            // uncomment below to test the property
            //modelInstance.resizable shouldBe ("TODO")
        }

        // to test the property `sortable` - sortable
        should("test sortable") {
            // uncomment below to test the property
            //modelInstance.sortable shouldBe ("TODO")
        }

        // to test the property `hideable` - hideable
        should("test hideable") {
            // uncomment below to test the property
            //modelInstance.hideable shouldBe ("TODO")
        }

        // to test the property `movable` - movable
        should("test movable") {
            // uncomment below to test the property
            //modelInstance.movable shouldBe ("TODO")
        }

        // to test the property `pinned` - pinned
        should("test pinned") {
            // uncomment below to test the property
            //modelInstance.pinned shouldBe ("TODO")
        }

        // to test the property `columnOrder` - columnOrder
        should("test columnOrder") {
            // uncomment below to test the property
            //modelInstance.columnOrder shouldBe ("TODO")
        }

        // to test the property `columnSortDirection` - columnSortDirection
        should("test columnSortDirection") {
            // uncomment below to test the property
            //modelInstance.columnSortDirection shouldBe ("TODO")
        }

        // to test the property `columnSortDirectionPriority` - columnSortDirectionPriority
        should("test columnSortDirectionPriority") {
            // uncomment below to test the property
            //modelInstance.columnSortDirectionPriority shouldBe ("TODO")
        }

    }
}
