/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.UpdateTunePreferences

class UpdateTunePreferencesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateTunePreferences
        //val modelInstance = UpdateTunePreferences()

        // to test the property `forceUpdatesToID3Tag` - whether or not the backend should apply the updates to the ID3 tags
        should("test forceUpdatesToID3Tag") {
            // uncomment below to test the property
            //modelInstance.forceUpdatesToID3Tag shouldBe ("TODO")
        }

    }
}
