/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.crates.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import io.crates.api.models.WatchFolderSettings
import io.crates.api.models.RefreshPolicy
import io.crates.api.models.WatchFolderPath

class WatchFolderSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WatchFolderSettings
        //val modelInstance = WatchFolderSettings()

        // to test the property `watchFolderPaths` - list of the watcher folders paths
        should("test watchFolderPaths") {
            // uncomment below to test the property
            //modelInstance.watchFolderPaths shouldBe ("TODO")
        }

        // to test the property `allowAudioTypes` - list of allowed audio types (default are mp3, flac, m4a
        should("test allowAudioTypes") {
            // uncomment below to test the property
            //modelInstance.allowAudioTypes shouldBe ("TODO")
        }

        // to test the property `lastModified` - wathcer folder's last modified date
        should("test lastModified") {
            // uncomment below to test the property
            //modelInstance.lastModified shouldBe ("TODO")
        }

        // to test the property `lastScanned` - wathcer folder's last scanned date
        should("test lastScanned") {
            // uncomment below to test the property
            //modelInstance.lastScanned shouldBe ("TODO")
        }

        // to test the property `refreshPolicy`
        should("test refreshPolicy") {
            // uncomment below to test the property
            //modelInstance.refreshPolicy shouldBe ("TODO")
        }

        // to test the property `initialDelayInSecs` - wathcer folder's initial delay (in secs) for scanning on init
        should("test initialDelayInSecs") {
            // uncomment below to test the property
            //modelInstance.initialDelayInSecs shouldBe ("TODO")
        }

    }
}
